# 〇〇の〇〇 カード辞書
TRAINER_POKEMON_DICT = {
    "アオキのノココッチ ex": "Larry's Dudunsparce ex",
"エリカのラフレシア ex": "Erika's Vileplume ex",
"ロケット団のワナイダー": "Team Rocket's Spidops",
"ロケット団のファイヤー ex": "Team Rocket's Moltres ex",
"カスミのコダック": "Misty's Psyduck",
"ロケット団のミュウツー ex": "Team Rocket's Mewtwo ex",
"ロケット団のソーナンス": "Team Rocket's Wobbuffet",
"ロケット団のイオルブ": "Team Rocket's Orbeetle",
"ロケット団のニドキング ex": "Team Rocket's Nidoking ex",
"ロケット団のクロバット ex": "Team Rocket's Crobat ex",
"ロケット団のマタドガス": "Team Rocket's Weezing",
"ロケット団のヤミカラス": "Team Rocket's Murkrow",
"ロケット団のラッタ": "Team Rocket's Raticate",
"ロケット団のニャース": "Team Rocket's Meowth",
"ロケット団のペルシアン": "Team Rocket's Persian",
"ペパーのマフィティフ ex": "Arven's Mabosstiff ex",
"ペパーのヨクバリス": "Arven's Greedent",
"ヒビキのバクフーン": "Ethan's Typhlosion",
"ヒビキのホウオウ ex": "Ethan's Ho-Oh ex",
"シロナのロズレイド": "Cynthia's Roserade",
"シロナのガブリアス ex": "Cynthia's Garchomp ex",
"シロナのガブリアス ex": "Cynthia's Garchomp",
"カスミのラプラス": "Misty's Lapras",
"マリィのオーロンゲ ex": "Marnie's Grimmsnarl ex",
"マリィのモルペコ": "Marnie's Morpeko",
"ダイゴのダンバル": "Steven's Beldum",
"ダイゴのメタグロス ex": "Steven's Metagross ex",
"Nのゾロアーク ex": "N's Zoroark ex",
"Nのレシラム": "N's Reshiram",
"Nのゼクロム": "N's Zekrom",
"リーリエのピッピ ex": "Lillie's Clefairy ex",
"リーリエのアブリボン": "Lillie's Ribombee",
"ナンジャモのハラバリー ex": "Iono's Bellibolt ex",
"ナンジャモのカイデン": "Iono's Wattrel",
"ナンジャモのタイカイデン": "Iono's Kilowattrel",
"ホップのザシアン ex": "Hop's Zacian ex",
"ホップのウールー": "Hop's Wooloo",
"ナツメのゲンガー": "Sabrina's Gengar",
"ワタルのカイリュー": "Lance's Dragonite",

    # ここに追加していく
}
POKEMON_TAG_DICT = {
    # 第1世代
    "MEWTWO": ["Mewtwo", "ミュウツー"],
    "MEW": ["Mew", "ミュウ"],
    "PIKACHU": ["Pikachu", "ピカチュウ"],
    "RAICHU": ["Raichu", "ライチュウ"],
    "PICHU": ["Pichu", "ピチュー"],
    "CHARIZARD": ["Charizard", "リザードン"],
    "CHARMELEON": ["Charmeleon", "リザード"],
    "CHARMANDER": ["Charmander", "ヒトカゲ"],
    "BLASTOISE": ["Blastoise", "カメックス"],
    "WARTORTLE": ["Wartortle", "カメール"],
    "SQUIRTLE": ["Squirtle", "ゼニガメ"],
    "VENUSAUR": ["Venusaur", "フシギバナ"],
    "IVYSAUR": ["Ivysaur", "フシギソウ"],
    "BULBASAUR": ["Bulbasaur", "フシギダネ"],
    "GENGAR": ["Gengar", "ゲンガー"],
    "HAUNTER": ["Haunter", "ゴースト"],
    "GASTLY": ["Gastly", "ゴース"],
    "ALAKAZAM": ["Alakazam", "フーディン"],
    "KADABRA": ["Kadabra", "ユンゲラー"],
    "ABRA": ["Abra", "ケーシィ"],
    "MACHAMP": ["Machamp", "カイリキー"],
    "GYARADOS": ["Gyarados", "ギャラドス"],
    "MAGIKARP": ["Magikarp", "コイキング"],
    "LAPRAS": ["Lapras", "ラプラス"],
    "ARCANINE": ["Arcanine", "ウインディ"],
    "GROWLITHE": ["Growlithe", "ガーディ"],
    "NINETALES": ["Ninetales", "キュウコン"],
    "VULPIX": ["Vulpix", "ロコン"],
    "SNORLAX": ["Snorlax", "カビゴン"],
    "DRAGONITE": ["Dragonite", "カイリュー"],
    "DRAGONAIR": ["Dragonair", "ハクリュー"],
    "DRATINI": ["Dratini", "ミニリュウ"],
    "CLEFAIRY": ["Clefairy", "ピッピ"],
    "CLEFABLE": ["Clefable", "ピクシー"],
    "JIGGLYPUFF": ["Jigglypuff", "プリン"],
    "WIGGLYTUFF": ["Wigglytuff", "プクリン"],
    "PSYDUCK": ["Psyduck", "コダック"],
    "GOLDUCK": ["Golduck", "ゴルダック"],
    "SLOWPOKE": ["Slowpoke", "ヤドン"],
    "SLOWBRO": ["Slowbro", "ヤドラン"],
    "SLOWKING": ["Slowking", "ヤドキング"],
    "CHANSEY": ["Chansey", "ラッキー"],
    "BLISSEY": ["Blissey", "ハピナス"],
    "MEOWTH": ["Meowth", "ニャース"],
    "PERSIAN": ["Persian", "ペルシアン"],
    "EEVEE": ["Eevee", "イーブイ"],
    "VAPOREON": ["Vaporeon", "シャワーズ"],
    "JOLTEON": ["Jolteon", "サンダース"],
    "FLAREON": ["Flareon", "ブースター"],
    "ESPEON": ["Espeon", "エーフィ"],
    "UMBREON": ["Umbreon", "ブラッキー"],
    "LEAFEON": ["Leafeon", "リーフィア"],
    "GLACEON": ["Glaceon", "グレイシア"],
    "SYLVEON": ["Sylveon", "ニンフィア"],
    "ARTICUNO": ["Articuno", "フリーザー"],
    "ZAPDOS": ["Zapdos", "サンダー"],
    "MOLTRES": ["Moltres", "ファイヤー"],
    "SCYTHER": ["Scyther", "ストライク"],
    "SCIZOR": ["Scizor", "ハッサム"],
    "PINSIR": ["Pinsir", "カイロス"],
    "AERODACTYL": ["Aerodactyl", "プテラ"],
    "SEEL": ["Seel", "パウワウ"],
    "DEWGONG": ["Dewgong", "ジュゴン"],
    "CLOYSTER": ["Cloyster", "パルシェン"],
    "SHELLDER": ["Shellder", "シェルダー"],
    "STARMIE": ["Starmie", "スターミー"],
    "STARYU": ["Staryu", "ヒトデマン"],
    "JYNX": ["Jynx", "ルージュラ"],
    "ELECTABUZZ": ["Electabuzz", "エレブー"],
    "MAGMAR": ["Magmar", "ブーバー"],
    "TAUROS": ["Tauros", "ケンタロス"],
    "PORYGON": ["Porygon", "ポリゴン"],
    "PORYGON2": ["Porygon2", "ポリゴン2"],
    "PORYGONZ": ["Porygon-Z", "ポリゴンZ"],
    "KANGASKHAN": ["Kangaskhan", "ガルーラ"],
    "DITTO": ["Ditto", "メタモン"],
    "MRMIME": ["Mr. Mime", "バリヤード"],
    "HITMONLEE": ["Hitmonlee", "サワムラー"],
    "HITMONCHAN": ["Hitmonchan", "エビワラー"],
    "HITMONTOP": ["Hitmontop", "カポエラー"],
    "LICKITUNG": ["Lickitung", "ベロリンガ"],
    "RHYDON": ["Rhydon", "サイドン"],
    "RHYHORN": ["Rhyhorn", "サイホーン"],
    "EXEGGUTOR": ["Exeggutor", "ナッシー"],
    "MAROWAK": ["Marowak", "ガラガラ"],
    "CUBONE": ["Cubone", "カラカラ"],
    "HYPNO": ["Hypno", "スリーパー"],
    "DROWZEE": ["Drowzee", "スリープ"],
    "VOLTORB": ["Voltorb", "ビリリダマ"],
    "ELECTRODE": ["Electrode", "マルマイン"],
    "WEEZING": ["Weezing", "マタドガス"],
    "KOFFING": ["Koffing", "ドガース"],
    "NIDOKING": ["Nidoking", "ニドキング"],
    "NIDOQUEEN": ["Nidoqueen", "ニドクイン"],
    "ONIX": ["Onix", "イワーク"],
    "STEELIX": ["Steelix", "ハガネール"],
    "GEODUDE": ["Geodude", "イシツブテ"],
    "GOLEM": ["Golem", "ゴローニャ"],
    "GRAVELER": ["Graveler", "ゴローン"],
    "TENTACRUEL": ["Tentacruel", "ドククラゲ"],
    "SKARMORY": ["Skarmory", "エアームド"],

    # 第2世代
    "LUGIA": ["Lugia", "ルギア"],
    "HOOH": ["Ho-Oh", "ホウオウ"],
    "CELEBI": ["Celebi", "セレビィ"],
    "ENTEI": ["Entei", "エンテイ"],
    "SUICUNE": ["Suicune", "スイクン"],
    "RAIKOU": ["Raikou", "ライコウ"],
    "TYRANITAR": ["Tyranitar", "バンギラス"],
    "AMPHAROS": ["Ampharos", "デンリュウ"],
    "FERALIGATR": ["Feraligatr", "オーダイル"],
    "MEGANIUM": ["Meganium", "メガニウム"],
    "TYPHLOSION": ["Typhlosion", "バクフーン"],
    "TOGEKISS": ["Togekiss", "トゲキッス"],
    "TOGETIC": ["Togetic", "トゲチック"],
    "TOGEPI": ["Togepi", "トゲピー"],
    "HERACROSS": ["Heracross", "ヘラクロス"],
    "HOUNDOOM": ["Houndoom", "ヘルガー"],
    "KINGDRA": ["Kingdra", "キングドラ"],
    "ESPEON": ["Espeon", "エーフィ"],
    "UMBREON": ["Umbreon", "ブラッキー"],
    "MISDREAVUS": ["Misdreavus", "ムウマ"],
    "WOBBUFFET": ["Wobbuffet", "ソーナンス"],
    "STANTLER": ["Stantler", "オドシシ"],
    "SMEARGLE": ["Smeargle", "ドーブル"],
    "SMOOCHUM": ["Smoochum", "ムチュール"],
    "ELEKID": ["Elekid", "エレキッド"],
    "MAGBY": ["Magby", "ブビィ"],
    "LARVITAR": ["Larvitar", "ヨーギラス"],

    # 第3世代
    "RAYQUAZA": ["Rayquaza", "レックウザ"],
    "GROUDON": ["Groudon", "グラードン"],
    "KYOGRE": ["Kyogre", "カイオーガ"],
    "BLAZIKEN": ["Blaziken", "バシャーモ"],
    "SWAMPERT": ["Swampert", "ラグラージ"],
    "SCEPTILE": ["Sceptile", "ジュカイン"],
    "GARDEVOIR": ["Gardevoir", "サーナイト"],
    "KIRLIA": ["Kirlia", "キルリア"],
    "RALTS": ["Ralts", "ラルトス"],
    "GALLADE": ["Gallade", "エルレイド"],
    "SALAMENCE": ["Salamence", "ボーマンダ"],
    "METAGROSS": ["Metagross", "メタグロス"],
    "LATIOS": ["Latios", "ラティオス"],
    "LATIAS": ["Latias", "ラティアス"],
    "JIRACHI": ["Jirachi", "ジラーチ"],
    "DEOXYS": ["Deoxys", "デオキシス"],
    "ABSOL": ["Absol", "アブソル"],
    "FLYGON": ["Flygon", "フライゴン"],
    "MILOTIC": ["Milotic", "ミロカロス"],
    "ALTARIA": ["Altaria", "チルタリス"],
    "ZANGOOSE": ["Zangoose", "ザングース"],
    "SEVIPER": ["Seviper", "ハブネーク"],

    # 第4世代
    "DIALGA": ["Dialga", "ディアルガ"],
    "PALKIA": ["Palkia", "パルキア"],
    "GIRATINA": ["Giratina", "ギラティナ"],
    "ARCEUS": ["Arceus", "アルセウス"],
    "DARKRAI": ["Darkrai", "ダークライ"],
    "SHAYMIN": ["Shaymin", "シェイミ"],
    "LUCARIO": ["Lucario", "ルカリオ"],
    "RIOLU": ["Riolu", "リオル"],
    "GARCHOMP": ["Garchomp", "ガブリアス"],
    "TOGEKISS": ["Togekiss", "トゲキッス"],
    "LEAFEON": ["Leafeon", "リーフィア"],
    "GLACEON": ["Glaceon", "グレイシア"],
    "ROTOM": ["Rotom", "ロトム"],
    "LUXRAY": ["Luxray", "レントラー"],
    "EMPOLEON": ["Empoleon", "エンペルト"],
    "INFERNAPE": ["Infernape", "ゴウカザル"],
    "TORTERRA": ["Torterra", "ドダイトス"],
    "MISMAGIUS": ["Mismagius", "ムウマージ"],
    "HIPPOWDON": ["Hippowdon", "カバルドン"],
    "WEAVILE": ["Weavile", "マニューラ"],
    "MAGNEZONE": ["Magnezone", "ジバコイル"],
    "ELECTIVIRE": ["Electivire", "エレキブル"],
    "MAGMORTAR": ["Magmortar", "ブウスター"],
    "TOGEKISS": ["Togekiss", "トゲキッス"],
    "PORYGONZ": ["Porygon-Z", "ポリゴンZ"],
    "CRESSELIA": ["Cresselia", "クレセリア"],
    "MANAPHY": ["Manaphy", "マナフィ"],
    "PHIONE": ["Phione", "フィオネ"],

    # 第5世代
    "RESHIRAM": ["Reshiram", "レシラム"],
    "ZEKROM": ["Zekrom", "ゼクロム"],
    "KYUREM": ["Kyurem", "キュレム"],
    "ZOROARK": ["Zoroark", "ゾロアーク"],
    "ZORUA": ["Zorua", "ゾロア"],
    "HYDREIGON": ["Hydreigon", "サザンドラ"],
    "VOLCARONA": ["Volcarona", "ウルガモス"],
    "CHANDELURE": ["Chandelure", "シャンデラ"],
    "KROOKODILE": ["Krookodile", "ワルビアル"],
    "EXCADRILL": ["Excadrill", "ドリュウズ"],
    "CONKELDURR": ["Conkeldurr", "ローブシン"],
    "VICTINI": ["Victini", "ビクティニ"],
    "GENESECT": ["Genesect", "ゲノセクト"],
    "MELOETTA": ["Meloetta", "メロエッタ"],
    "COBALION": ["Cobalion", "コバルオン"],
    "TERRAKION": ["Terrakion", "テラキオン"],
    "VIRIZION": ["Virizion", "ビリジオン"],
    "THUNDURUS": ["Thundurus", "ボルトロス"],
    "TORNADUS": ["Tornadus", "トルネロス"],
    "LANDORUS": ["Landorus", "ランドロス"],
    "SERPERIOR": ["Serperior", "ジャローダ"],
    "EMBOAR": ["Emboar", "エンブオー"],
    "SAMUROTT": ["Samurott", "ダイケンキ"],

    # 第6世代
    "XERNEAS": ["Xerneas", "ゼルネアス"],
    "YVELTAL": ["Yveltal", "イベルタル"],
    "ZYGARDE": ["Zygarde", "ジガルデ"],
    "DIANCIE": ["Diancie", "ディアンシー"],
    "HOOPA": ["Hoopa", "フーパ"],
    "VOLCANION": ["Volcanion", "ボルケニオン"],
    "GRENINJA": ["Greninja", "ゲッコウガ"],
    "CHESNAUGHT": ["Chesnaught", "ブリガロン"],
    "DELPHOX": ["Delphox", "マフォクシー"],
    "SYLVEON": ["Sylveon", "ニンフィア"],
    "AEGISLASH": ["Aegislash", "ギルガルド"],
    "TYRANTRUM": ["Tyrantrum", "ガチゴラス"],
    "GOODRA": ["Goodra", "ヌメルゴン"],
    "NOIVERN": ["Noivern", "オンバーン"],
    "TALONFLAME": ["Talonflame", "ファイアロー"],
    "HAWLUCHA": ["Hawlucha", "ルチャブル"],

    # 第7世代
    "SOLGALEO": ["Solgaleo", "ソルガレオ"],
    "LUNALA": ["Lunala", "ルナアーラ"],
    "NECROZMA": ["Necrozma", "ネクロズマ"],
    "MARSHADOW": ["Marshadow", "マーシャドー"],
    "ZERAORA": ["Zeraora", "ゼラオラ"],
    "MAGEARNA": ["Magearna", "マギアナ"],
    "MIMIKYU": ["Mimikyu", "ミミッキュ"],
    "KOMMO-O": ["Kommo-o", "ジャラランガ"],
    "TOXAPEX": ["Toxapex", "ドヒドイデ"],
    "WISHIWASHI": ["Wishiwashi", "ヨワシ"],
    "BEWEAR": ["Bewear", "キテルグマ"],
    "DECIDUEYE": ["Decidueye", "ジュナイパー"],
    "INCINEROAR": ["Incineroar", "ガオガエン"],
    "PRIMARINA": ["Primarina", "アシレーヌ"],
    "TAPU KOKO": ["Tapu Koko", "カプ・コケコ"],
    "TAPULELE": ["Tapu Lele", "カプ・テテフ"],
    "TAPUBULU": ["Tapu Bulu", "カプ・ブルル"],
    "TAPUFINI": ["Tapu Fini", "カプ・レヒレ"],
    "ORICORIO": ["Oricorio", "オドリドリ"],

    # 第8世代
    "ZACIAN": ["Zacian", "ザシアン"],
    "ZAMAZENTA": ["Zamazenta", "ザマゼンタ"],
    "ETERNATUS": ["Eternatus", "ムゲンダイナ"],
    "CALYREX": ["Calyrex", "バドレックス"],
    "ZARUDE": ["Zarude", "ザルード"],
    "REGIELEKI": ["Regieleki", "レジエレキ"],
    "REGIDRAGO": ["Regidrago", "レジドラゴ"],
    "GLASTRIER": ["Glastrier", "ブリザポス"],
    "SPECTRIER": ["Spectrier", "レイスポス"],
    "URSHIFU": ["Urshifu", "ウーラオス"],
    "CINDERACE": ["Cinderace", "エースバーン"],
    "INTELEON": ["Inteleon", "インテレオン"],
    "RILLABOOM": ["Rillaboom", "ゴリランダー"],
    "DRAGAPULT": ["Dragapult", "ドラパルト"],
    "TOXTRICITY": ["Toxtricity", "ストリンダー"],
    "GRIMMSNARL": ["Grimmsnarl", "オーロンゲ"],
    "OBSTAGOON": ["Obstagoon", "タチフサグマ"],
    "ALCREMIE": ["Alcremie", "マホイップ"],
    "DRACOVISH": ["Dracovish", "ウオチルドン"],
    "EISCUE": ["Eiscue", "コオリッポ"],
    "MORPEKO": ["Morpeko", "モルペコ"],

    # 第9世代
    "KORAIDON": ["Koraidon", "コライドン"],
    "MIRAIDON": ["Miraidon", "ミライドン"],
    "MEOWSCARADA": ["Meowscarada", "マスカーニャ"],
    "SKELEDIRGE": ["Skeledirge", "ソウブレイズ"],
    "QUAQUAVAL": ["Quaquaval", "ウェーニバル"],
    "SPRIGATITO": ["Sprigatito", "ニャオハ"],
    "FUECOCO": ["Fuecoco", "ホゲータ"],
    "QUAXLY": ["Quaxly", "クワッス"],
    "PALAFIN": ["Palafin", "イルカマン"],
    "TINKATON": ["Tinkaton", "デカヌチャン"],
    "ANNIHILAPE": ["Annihilape", "コノヨザル"],
    "CLODSIRE": ["Clodsire", "ドオー"],
    "DONDOZO": ["Dondozo", "ヘイラッシャ"],
    "TATSUGIRI": ["Tatsugiri", "タツギリ"],
    "GHOLDENGO": ["Gholdengo", "サーフゴー"],
    "ROARING MOON": ["Roaring Moon", "チヲハウハネ"],
    "IRONVALIANT": ["Iron Valiant", "テツノブジン"],
    "IRONMOTH": ["Iron Moth", "テツノドクガ"],
    "IRONCROWN": ["Iron Crown", "テツノカシラ"],
    "IRONTHORNS": ["Iron Thorns", "テツノイバラ"],
    "FLUTTERMANE": ["Flutter Mane", "ハバタクカミ"],
    "MUNKIDORI": ["Munkidori", "マシマシラ"],
    "OKIDOGI": ["Okidogi", "イイネイヌ"],
    "FEZANDIPITI": ["Fezandipiti", "マシマシラ"],
    "OGERPON": ["Ogerpon", "オーガポン"],
    "TERAPAGOS": ["Terapagos", "テラパゴス"],
    "PECHARUNT": ["Pecharunt", "モモワロウ"],
    # 第1世代（未登録分）
    "NIDORANF": ["Nidoran♀", "ニドラン♀"],
    "NIDORINA": ["Nidorina", "ニドリーナ"],
    "NIDOQUEEN": ["Nidoqueen", "ニドクイン"],
    "NIDORANM": ["Nidoran♂", "ニドラン♂"],
    "NIDORINO": ["Nidorino", "ニドリーノ"],
    "NIDOKING": ["Nidoking", "ニドキング"],
    "ZUBAT": ["Zubat", "ズバット"],
    "GOLBAT": ["Golbat", "ゴルバット"],
    "CROBAT": ["Crobat", "クロバット"],
    "ODDISH": ["Oddish", "ナゾノクサ"],
    "GLOOM": ["Gloom", "クサイハナ"],
    "VILEPLUME": ["Vileplume", "ラフレシア"],
    "BELLOSSOM": ["Bellossom", "キレイハナ"],
    "PARAS": ["Paras", "パラス"],
    "PARASECT": ["Parasect", "パラセクト"],
    "VENONAT": ["Venonat", "コンパン"],
    "VENOMOTH": ["Venomoth", "モルフォン"],
    "DIGLETT": ["Diglett", "ディグダ"],
    "DUGTRIO": ["Dugtrio", "ダグトリオ"],
    "MANKEY": ["Mankey", "マンキー"],
    "PRIMEAPE": ["Primeape", "オコリザル"],
    "ANNIHILAPE": ["Annihilape", "コノヨザル"],
    "POLIWAG": ["Poliwag", "ニョロモ"],
    "POLIWHIRL": ["Poliwhirl", "ニョロゾ"],
    "POLIWRATH": ["Poliwrath", "ニョロボン"],
    "POLITOED": ["Politoed", "ニョロトノ"],
    "BELLSPROUT": ["Bellsprout", "マダツボミ"],
    "WEEPINBELL": ["Weepinbell", "ウツドン"],
    "VICTREEBEL": ["Victreebel", "ウツボット"],
    "TENTACOOL": ["Tentacool", "メノクラゲ"],
    "TENTACRUEL": ["Tentacruel", "ドククラゲ"],
    "PONYTA": ["Ponyta", "ポニータ"],
    "RAPIDASH": ["Rapidash", "ギャロップ"],
    "FARFETCHD": ["Farfetch'd", "カモネギ"],
    "DODUO": ["Doduo", "ドードー"],
    "DODRIO": ["Dodrio", "ドードリオ"],
    "GRIMER": ["Grimer", "ベトベター"],
    "MUK": ["Muk", "ベトベトン"],
    "GASTLY": ["Gastly", "ゴース"],
    "HAUNTER": ["Haunter", "ゴースト"],
    "ONIX": ["Onix", "イワーク"],
    "DROWZEE": ["Drowzee", "スリープ"],
    "HYPNO": ["Hypno", "スリーパー"],
    "KRABBY": ["Krabby", "クラブ"],
    "KINGLER": ["Kingler", "キングラー"],
    "VOLTORB": ["Voltorb", "ビリリダマ"],
    "ELECTRODE": ["Electrode", "マルマイン"],
    "EXEGGCUTE": ["Exeggcute", "タマタマ"],
    "EXEGGUTOR": ["Exeggutor", "ナッシー"],
    "CUBONE": ["Cubone", "カラカラ"],
    "MAROWAK": ["Marowak", "ガラガラ"],
    "LICKITUNG": ["Lickitung", "ベロリンガ"],
    "LICKILICKY": ["Lickilicky", "ベロベルト"],
    "KOFFING": ["Koffing", "ドガース"],
    "WEEZING": ["Weezing", "マタドガス"],
    "RHYHORN": ["Rhyhorn", "サイホーン"],
    "RHYDON": ["Rhydon", "サイドン"],
    "RHYPERIOR": ["Rhyperior", "ドサイドン"],
    "CHANSEY": ["Chansey", "ラッキー"],
    "BLISSEY": ["Blissey", "ハピナス"],
    "TANGELA": ["Tangela", "モンジャラ"],
    "TANGROWTH": ["Tangrowth", "モジャンボ"],
    "HORSEA": ["Horsea", "タッツー"],
    "SEADRA": ["Seadra", "シードラ"],
    "KINGDRA": ["Kingdra", "キングドラ"],
    "GOLDEEN": ["Goldeen", "トサキント"],
    "SEAKING": ["Seaking", "アズマオウ"],
    "SCYTHER": ["Scyther", "ストライク"],
    "ELECTABUZZ": ["Electabuzz", "エレブー"],
    "ELECTIVIRE": ["Electivire", "エレキブル"],
    "MAGMAR": ["Magmar", "ブーバー"],
    "MAGMORTAR": ["Magmortar", "ブウスター"],
    "PINSIR": ["Pinsir", "カイロス"],
    "TAUROS": ["Tauros", "ケンタロス"],
    "EEVEE": ["Eevee", "イーブイ"],
    "PORYGON": ["Porygon", "ポリゴン"],
    "PORYGON2": ["Porygon2", "ポリゴン2"],
    "PORYGONZ": ["Porygon-Z", "ポリゴンZ"],
    "OMANYTE": ["Omanyte", "オムナイト"],
    "OMASTAR": ["Omastar", "オムスター"],
    "KABUTO": ["Kabuto", "カブト"],
    "KABUTOPS": ["Kabutops", "カブトプス"],
    "SNORLAX": ["Snorlax", "カビゴン"],
    "DITTO": ["Ditto", "メタモン"],
    "MRMIME": ["Mr. Mime", "バリヤード"],
    "MRMIME2": ["Mr. Rime", "バリコオル"],
    "JYNX": ["Jynx", "ルージュラ"],
    "SMOOCHUM": ["Smoochum", "ムチュール"],

    # 第2世代（未登録分）
    "CHIKORITA": ["Chikorita", "チコリータ"],
    "BAYLEEF": ["Bayleef", "ベイリーフ"],
    "MEGANIUM": ["Meganium", "メガニウム"],
    "CYNDAQUIL": ["Cyndaquil", "ヒノアラシ"],
    "QUILAVA": ["Quilava", "マグマラシ"],
    "TYPHLOSION": ["Typhlosion", "バクフーン"],
    "TOTODILE": ["Totodile", "ワニノコ"],
    "CROCONAW": ["Croconaw", "アリゲイツ"],
    "FERALIGATR": ["Feraligatr", "オーダイル"],
    "SENTRET": ["Sentret", "オタチ"],
    "FURRET": ["Furret", "オオタチ"],
    "HOOTHOOT": ["Hoothoot", "ホーホー"],
    "NOCTOWL": ["Noctowl", "ヨルノズク"],
    "LEDYBA": ["Ledyba", "レディバ"],
    "LEDIAN": ["Ledian", "レディアン"],
    "SPINARAK": ["Spinarak", "イトマル"],
    "ARIADOS": ["Ariados", "アリアドス"],
    "CHINCHOU": ["Chinchou", "チョンチー"],
    "LANTURN": ["Lanturn", "ランターン"],
    "PICHU": ["Pichu", "ピチュー"],
    "CLEFFA": ["Cleffa", "ピィ"],
    "IGGLYBUFF": ["Igglybuff", "ププリン"],
    "TOGEPI": ["Togepi", "トゲピー"],
    "TOGETIC": ["Togetic", "トゲチック"],
    "NATU": ["Natu", "ネイティ"],
    "XATU": ["Xatu", "ネイティオ"],
    "MAREEP": ["Mareep", "メリープ"],
    "FLAAFFY": ["Flaaffy", "モコシープ"],
    "AMPHAROS": ["Ampharos", "デンリュウ"],
    "MARILL": ["Marill", "マリル"],
    "AZUMARILL": ["Azumarill", "マリルリ"],
    "SUDOWOODO": ["Sudowoodo", "ウソッキー"],
    "AIPOM": ["Aipom", "エイパム"],
    "AMBIPOM": ["Ambipom", "エテボース"],
    "SUNKERN": ["Sunkern", "ヒマナッツ"],
    "SUNFLORA": ["Sunflora", "キマワリ"],
    "YANMA": ["Yanma", "ヤンヤンマ"],
    "YANMEGA": ["Yanmega", "メガヤンマ"],
    "WOOPER": ["Wooper", "ウパー"],
    "QUAGSIRE": ["Quagsire", "ヌオー"],
    "MURKROW": ["Murkrow", "ヤミカラス"],
    "HONCHKROW": ["Honchkrow", "ドンカラス"],
    "MISDREAVUS": ["Misdreavus", "ムウマ"],
    "MISMAGIUS": ["Mismagius", "ムウマージ"],
    "UNOWN": ["Unown", "アンノーン"],
    "WOBBUFFET": ["Wobbuffet", "ソーナンス"],
    "GIRAFARIG": ["Girafarig", "キリンリキ"],
    "FARIGIRAF": ["Farigiraf", "リキキリン"],
    "PINECO": ["Pineco", "クヌギダマ"],
    "FORRETRESS": ["Forretress", "フォレトス"],
    "DUNSPARCE": ["Dunsparce", "ノコッチ"],
    "GLIGAR": ["Gligar", "グライガー"],
    "GLISCOR": ["Gliscor", "グライオン"],
    "SNUBBULL": ["Snubbull", "ブルー"],
    "GRANBULL": ["Granbull", "グランブル"],
    "QWILFISH": ["Qwilfish", "ハリーセン"],
    "SHUCKLE": ["Shuckle", "ツボツボ"],
    "HERACROSS": ["Heracross", "ヘラクロス"],
    "SNEASEL": ["Sneasel", "ニューラ"],
    "WEAVILE": ["Weavile", "マニューラ"],
    "TEDDIURSA": ["Teddiursa", "ヒメグマ"],
    "URSARING": ["Ursaring", "リングマ"],
    "URSALUNA": ["Ursaluna", "ガチグマ"],
    "SLUGMA": ["Slugma", "マグマッグ"],
    "MAGCARGO": ["Magcargo", "マグカルゴ"],
    "SWINUB": ["Swinub", "ウリムー"],
    "PILOSWINE": ["Piloswine", "イノムー"],
    "MAMOSWINE": ["Mamoswine", "マンムー"],
    "CORSOLA": ["Corsola", "サニーゴ"],
    "REMORAID": ["Remoraid", "テッポウオ"],
    "OCTILLERY": ["Octillery", "オクタン"],
    "DELIBIRD": ["Delibird", "デリバード"],
    "MANTINE": ["Mantine", "マンタイン"],
    "MANTYKE": ["Mantyke", "タマンタ"],
    "HOUNDOUR": ["Houndour", "デルビル"],
    "HOUNDOOM": ["Houndoom", "ヘルガー"],
    "PHANPY": ["Phanpy", "ゴマゾウ"],
    "DONPHAN": ["Donphan", "ドンファン"],
    "STANTLER": ["Stantler", "オドシシ"],
    "WYRDEER": ["Wyrdeer", "シキジカ"],
    "SMEARGLE": ["Smeargle", "ドーブル"],
    "TYROGUE": ["Tyrogue", "バルキー"],
    "HITMONTOP": ["Hitmontop", "カポエラー"],
    "ELEKID": ["Elekid", "エレキッド"],
    "MAGBY": ["Magby", "ブビィ"],
    "MILTANK": ["Miltank", "ミルタンク"],
    "LARVITAR": ["Larvitar", "ヨーギラス"],
    "PUPITAR": ["Pupitar", "サナギラス"],
    "TYRANITAR": ["Tyranitar", "バンギラス"],

    # 第3世代（未登録分）
    "TREECKO": ["Treecko", "キモリ"],
    "GROVYLE": ["Grovyle", "ジュプトル"],
    "TORCHIC": ["Torchic", "アチャモ"],
    "COMBUSKEN": ["Combusken", "ワカシャモ"],
    "MUDKIP": ["Mudkip", "ミズゴロウ"],
    "MARSHTOMP": ["Marshtomp", "ヌマクロー"],
    "POOCHYENA": ["Poochyena", "ポチエナ"],
    "MIGHTYENA": ["Mightyena", "グラエナ"],
    "ZIGZAGOON": ["Zigzagoon", "ジグザグマ"],
    "LINOONE": ["Linoone", "マッスグマ"],
    "OBSTAGOON": ["Obstagoon", "タチフサグマ"],
    "WURMPLE": ["Wurmple", "ケムッソ"],
    "SILCOON": ["Silcoon", "カラサリス"],
    "BEAUTIFLY": ["Beautifly", "アゲハント"],
    "CASCOON": ["Cascoon", "マユルド"],
    "DUSTOX": ["Dustox", "ドクケイル"],
    "LOTAD": ["Lotad", "ハスボー"],
    "LOMBRE": ["Lombre", "ハスブレロ"],
    "LUDICOLO": ["Ludicolo", "ルンパッパ"],
    "SEEDOT": ["Seedot", "タネボー"],
    "NUZLEAF": ["Nuzleaf", "コノハナ"],
    "SHIFTRY": ["Shiftry", "ダーテング"],
    "TAILLOW": ["Taillow", "スバメ"],
    "SWELLOW": ["Swellow", "オオスバメ"],
    "WINGULL": ["Wingull", "キャモメ"],
    "PELIPPER": ["Pelipper", "ペリッパー"],
    "RALTS": ["Ralts", "ラルトス"],
    "KIRLIA": ["Kirlia", "キルリア"],
    "GALLADE": ["Gallade", "エルレイド"],
    "SURSKIT": ["Surskit", "アメタマ"],
    "MASQUERAIN": ["Masquerain", "アメモース"],
    "SHROOMISH": ["Shroomish", "キノコ"],
    "BRELOOM": ["Breloom", "キノガッサ"],
    "SLAKOTH": ["Slakoth", "ナマケロ"],
    "VIGOROTH": ["Vigoroth", "ヤルキモノ"],
    "SLAKING": ["Slaking", "ケッキング"],
    "NINCADA": ["Nincada", "ツチニン"],
    "NINJASK": ["Ninjask", "テッカニン"],
    "SHEDINJA": ["Shedinja", "ヌケニン"],
    "WHISMUR": ["Whismur", "ゴニョニョ"],
    "LOUDRED": ["Loudred", "ドゴーム"],
    "EXPLOUD": ["Exploud", "バクオング"],
    "MAKUHITA": ["Makuhita", "マクノシタ"],
    "HARIYAMA": ["Hariyama", "ハリテヤマ"],
    "NOSEPASS": ["Nosepass", "ノズパス"],
    "PROBOPASS": ["Probopass", "ダイノーズ"],
    "SKITTY": ["Skitty", "エネコ"],
    "DELCATTY": ["Delcatty", "エネコロロ"],
    "SABLEYE": ["Sableye", "ヤミラミ"],
    "MAWILE": ["Mawile", "クチート"],
    "ARON": ["Aron", "ココドラ"],
    "LAIRON": ["Lairon", "コドラ"],
    "AGGRON": ["Aggron", "ボスゴドラ"],
    "MEDITITE": ["Meditite", "アサナン"],
    "MEDICHAM": ["Medicham", "チャーレム"],
    "ELECTRIKE": ["Electrike", "rakurai"],
    "MANECTRIC": ["Manectric", "ライボルト"],
    "PLUSLE": ["Plusle", "プラスル"],
    "MINUN": ["Minun", "マイナン"],
    "VOLBEAT": ["Volbeat", "バルビート"],
    "ILLUMISE": ["Illumise", "イルミーゼ"],
    "ROSELIA": ["Roselia", "ロゼリア"],
    "ROSERADE": ["Roserade", "ロズレイド"],
    "GULPIN": ["Gulpin", "ゴクリン"],
    "SWALOT": ["Swalot", "マルノーム"],
    "CARVANHA": ["Carvanha", "キバニア"],
    "SHARPEDO": ["Sharpedo", "サメハダー"],
    "WAILMER": ["Wailmer", "ホエルコ"],
    "WAILORD": ["Wailord", "ホエルオー"],
    "NUMEL": ["Numel", "ドンメル"],
    "CAMERUPT": ["Camerupt", "バクーダ"],
    "TORKOAL": ["Torkoal", "コータス"],
    "SPOINK": ["Spoink", "バネブー"],
    "GRUMPIG": ["Grumpig", "ブーピッグ"],
    "SPINDA": ["Spinda", "パッチール"],
    "TRAPINCH": ["Trapinch", "ナックラー"],
    "VIBRAVA": ["Vibrava", "ビブラーバ"],
    "CACNEA": ["Cacnea", "サボネア"],
    "CACTURNE": ["Cacturne", "ノクタス"],
    "SWABLU": ["Swablu", "チルット"],
    "SEVIPER": ["Seviper", "ハブネーク"],
    "LUNATONE": ["Lunatone", "ルナトーン"],
    "SOLROCK": ["Solrock", "ソルロック"],
    "BARBOACH": ["Barboach", "ドジョッチ"],
    "WHISCASH": ["Whiscash", "ナマズン"],
    "CORPHISH": ["Corphish", "ヘイガニ"],
    "CRAWDAUNT": ["Crawdaunt", "シザリガー"],
    "BALTOY": ["Baltoy", "ヤジロン"],
    "CLAYDOL": ["Claydol", "ネンドール"],
    "LILEEP": ["Lileep", "リリーラ"],
    "CRADILY": ["Cradily", "ユレイドル"],
    "ANORITH": ["Anorith", "アノプス"],
    "ARMALDO": ["Armaldo", "アーマルド"],
    "FEEBAS": ["Feebas", "ヒンバス"],
    "CASTFORM": ["Castform", "ポワルン"],
    "KECLEON": ["Kecleon", "カクレオン"],
    "SHUPPET": ["Shuppet", "カゲボウズ"],
    "BANETTE": ["Banette", "ジュペッタ"],
    "DUSKULL": ["Duskull", "ヨマワル"],
    "DUSCLOPS": ["Dusclops", "ヨノワール"],
    "TROPIUS": ["Tropius", "トロピウス"],
    "CHIMECHO": ["Chimecho", "チリーン"],
    "WYNAUT": ["Wynaut", "ソーナノ"],
    "SNORUNT": ["Snorunt", "ユキワラシ"],
    "GLALIE": ["Glalie", "オニゴーリ"],
    "FROSLASS": ["Froslass", "ユキメノコ"],
    "SPHEAL": ["Spheal", "タマザラシ"],
    "SEALEO": ["Sealeo", "トドグラー"],
    "WALREIN": ["Walrein", "トドゼルガ"],
    "CLAMPERL": ["Clamperl", "パールル"],
    "HUNTAIL": ["Huntail", "ハンテール"],
    "GOREBYSS": ["Gorebyss", "サクラビス"],
    "RELICANTH": ["Relicanth", "ジーランス"],
    "LUVDISC": ["Luvdisc", "ラブカス"],
    "BAGON": ["Bagon", "タツベイ"],
    "SHELGON": ["Shelgon", "コモルー"],
    "BELDUM": ["Beldum", "ダンバル"],
    "METANG": ["Metang", "メタング"],
    "REGIROCK": ["Regirock", "レジロック"],
    "REGICE": ["Regice", "レジアイス"],
    "REGISTEEL": ["Registeel", "レジスチル"],
    "REGIGIGAS": ["Regigigas", "レジギガス"],
    "REGIELEKI": ["Regieleki", "レジエレキ"],
    "REGIDRAGO": ["Regidrago", "レジドラゴ"],
    "KYOGRE": ["Kyogre", "カイオーガ"],
    "GROUDON": ["Groudon", "グラードン"],
    "NINCADA": ["Nincada", "ツチニン"],

    # 第4世代（未登録分）
    "TURTWIG": ["Turtwig", "ナエトル"],
    "GROTLE": ["Grotle", "ハヤシガメ"],
    "CHIMCHAR": ["Chimchar", "ヒコザル"],
    "MONFERNO": ["Monferno", "モウカザル"],
    "PIPLUP": ["Piplup", "ポッチャマ"],
    "PRINPLUP": ["Prinplup", "ポッタイシ"],
    "STARLY": ["Starly", "ムックル"],
    "STARAVIA": ["Staravia", "ムクバード"],
    "STARAPTOR": ["Staraptor", "ムクホーク"],
    "BIDOOF": ["Bidoof", "ビッパ"],
    "BIBAREL": ["Bibarel", "ビーダル"],
    "KRICKETOT": ["Kricketot", "コロボーシ"],
    "KRICKETUNE": ["Kricketune", "コロトック"],
    "SHINX": ["Shinx", "コリンク"],
    "LUXIO": ["Luxio", "ルクシオ"],
    "BUDEW": ["Budew", "スボミー"],
    "CRANIDOS": ["Cranidos", "ズガイドス"],
    "RAMPARDOS": ["Rampardos", "ラムパルド"],
    "SHIELDON": ["Shieldon", "タテトプス"],
    "BASTIODON": ["Bastiodon", "トリデプス"],
    "BURMY": ["Burmy", "ミノムッチ"],
    "WORMADAM": ["Wormadam", "ミノマダム"],
    "MOTHIM": ["Mothim", "ガーメイル"],
    "COMBEE": ["Combee", "ミツハニー"],
    "VESPIQUEN": ["Vespiquen", "ビークイン"],
    "PACHIRISU": ["Pachirisu", "パチリス"],
    "BUIZEL": ["Buizel", "ブイゼル"],
    "FLOATZEL": ["Floatzel", "フローゼル"],
    "CHERUBI": ["Cherubi", "チェリンボ"],
    "CHERRIM": ["Cherrim", "チェリム"],
    "SHELLOS": ["Shellos", "カラナクシ"],
    "GASTRODON": ["Gastrodon", "トリトドン"],
    "DRIFLOON": ["Drifloon", "フワンテ"],
    "DRIFBLIM": ["Drifblim", "フワライド"],
    "BUNEARY": ["Buneary", "ミミロル"],
    "LOPUNNY": ["Lopunny", "ミミロップ"],
    "GLAMEOW": ["Glameow", "ニャルマー"],
    "PURUGLY": ["Purugly", "ブニャット"],
    "CHINGLING": ["Chingling", "リーシャン"],
    "STUNKY": ["Stunky", "スカンプー"],
    "SKUNTANK": ["Skuntank", "スカタンク"],
    "BRONZOR": ["Bronzor", "ドーミラー"],
    "BRONZONG": ["Bronzong", "ドータクン"],
    "BONSLY": ["Bonsly", "ウソハチ"],
    "MIME JR": ["Mime Jr.", "マネネ"],
    "HAPPINY": ["Happiny", "ピンプク"],
    "CHATOT": ["Chatot", "ペラップ"],
    "SPIRITOMB": ["Spiritomb", "ミカルゲ"],
    "GIBLE": ["Gible", "フカマル"],
    "GABITE": ["Gabite", "ガバイト"],
    "MUNCHLAX": ["Munchlax", "ゴンベ"],
    "RIOLU": ["Riolu", "リオル"],
    "HIPPOPOTAS": ["Hippopotas", "ヒポポタス"],
    "SKORUPI": ["Skorupi", "スコルピ"],
    "DRAPION": ["Drapion", "ドラピオン"],
    "CROAGUNK": ["Croagunk", "グレッグル"],
    "TOXICROAK": ["Toxicroak", "ドクロッグ"],
    "CARNIVINE": ["Carnivine", "マスキッパ"],
    "FINNEON": ["Finneon", "ケイコウオ"],
    "LUMINEON": ["Lumineon", "ネオラント"],
    "SNOVER": ["Snover", "ユキカブリ"],
    "ABOMASNOW": ["Abomasnow", "ユキノオー"],
    "FROSLASS": ["Froslass", "ユキメノコ"],
    "UXIE": ["Uxie", "ユクシー"],
    "MESPRIT": ["Mesprit", "エムリット"],
    "AZELF": ["Azelf", "アグノム"],
    "HEATRAN": ["Heatran", "ヒードラン"],
    "PHIONE": ["Phione", "フィオネ"],
    "MANAPHY": ["Manaphy", "マナフィ"],
    "CRESSELIA": ["Cresselia", "クレセリア"],

    # 第5世代（未登録分）
    "SNIVY": ["Snivy", "ツタージャ"],
    "SERVINE": ["Servine", "ジャノビー"],
    "TEPIG": ["Tepig", "ポカブ"],
    "PIGNITE": ["Pignite", "チャオブー"],
    "OSHAWOTT": ["Oshawott", "ミジュマル"],
    "DEWOTT": ["Dewott", "フタチマル"],
    "PATRAT": ["Patrat", "ミネズミ"],
    "WATCHOG": ["Watchog", "ミルホッグ"],
    "LILLIPUP": ["Lillipup", "yorterrie"],
    "HERDIER": ["Herdier", "ハーデリア"],
    "STOUTLAND": ["Stoutland", "ムーランド"],
    "PURRLOIN": ["Purrloin", "チョロネコ"],
    "LIEPARD": ["Liepard", "レパルダス"],
    "PANSAGE": ["Pansage", "ヤナップ"],
    "SIMISAGE": ["Simisage", "ヤナッキー"],
    "PANSEAR": ["Pansear", "バオップ"],
    "SIMISEAR": ["Simisear", "バオッキー"],
    "PANPOUR": ["Panpour", "ヒヤップ"],
    "SIMIPOUR": ["Simipour", "ヒヤッキー"],
    "MUNNA": ["Munna", "ムンナ"],
    "MUSHARNA": ["Musharna", "ムシャーナ"],
    "PIDOVE": ["Pidove", "マメパト"],
    "TRANQUILL": ["Tranquill", "ハトーボー"],
    "UNFEZANT": ["Unfezant", "ケンホロウ"],
    "BLITZLE": ["Blitzle", "シママ"],
    "ZEBSTRIKA": ["Zebstrika", "ゼブライカ"],
    "ROGGENROLA": ["Roggenrola", "ダンゴロ"],
    "BOLDORE": ["Boldore", "ガントル"],
    "GIGALITH": ["Gigalith", "ギガイアス"],
    "WOOBAT": ["Woobat", "コロモリ"],
    "SWOOBAT": ["Swoobat", "ランクルス"],
    "DRILBUR": ["Drilbur", "モグリュー"],
    "AUDINO": ["Audino", "tabunne"],
    "TIMBURR": ["Timburr", "ドッコラー"],
    "GURDURR": ["Gurdurr", "ドテッコツ"],
    "TYMPOLE": ["Tympole", "オタマロ"],
    "PALPITOAD": ["Palpitoad", "ガマガル"],
    "SEISMITOAD": ["Seismitoad", "ガマゲロゲ"],
    "THROH": ["Throh", "ナゲキ"],
    "SAWK": ["Sawk", "ダゲキ"],
    "SEWADDLE": ["Sewaddle", "クルミル"],
    "SWADLOON": ["Swadloon", "クルマユ"],
    "LEAVANNY": ["Leavanny", "ハハコモリ"],
    "VENIPEDE": ["Venipede", "フシデ"],
    "WHIRLIPEDE": ["Whirlipede", "hoiiga"],
    "SCOLIPEDE": ["Scolipede", "ペンドラー"],
    "COTTONEE": ["Cottonee", "モンメン"],
    "WHIMSICOTT": ["Whimsicott", "エルフーン"],
    "PETILIL": ["Petilil", "チュリネ"],
    "LILLIGANT": ["Lilligant", "ドレディア"],
    "SANDILE": ["Sandile", "メグロコ"],
    "KROKOROK": ["Krokorok", "ワルビル"],
    "DARUMAKA": ["Darumaka", "ダルマッカ"],
    "DARMANITAN": ["Darmanitan", "ヒヒダルマ"],
    "MARACTUS": ["Maractus", "マラカッチ"],
    "SCRAGGY": ["Scraggy", "ズルッグ"],
    "SCRAFTY": ["Scrafty", "ズルズキン"],
    "SIGILYPH": ["Sigilyph", "シンボラー"],
    "YAMASK": ["Yamask", "デスマス"],
    "COFAGRIGUS": ["Cofagrigus", "デスカーン"],
    "TIRTOUGA": ["Tirtouga", "プロトーガ"],
    "CARRACOSTA": ["Carracosta", "アバゴーラ"],
    "ARCHEN": ["Archen", "アーケン"],
    "ARCHEOPS": ["Archeops", "アーケオス"],
    "TRUBBISH": ["Trubbish", "ヤブクロン"],
    "GARBODOR": ["Garbodor", "ダストダス"],
    "MINCCINO": ["Minccino", "チラーミィ"],
    "CINCCINO": ["Cinccino", "チラチーノ"],
    "GOTHITA": ["Gothita", "ゴチム"],
    "GOTHORITA": ["Gothorita", "ゴチミル"],
    "GOTHITELLE": ["Gothitelle", "ゴチルゼル"],
    "SOLOSIS": ["Solosis", "ユニラン"],
    "DUOSION": ["Duosion", "ダブラン"],
    "REUNICLUS": ["Reuniclus", "ランクルス"],
    "DUCKLETT": ["Ducklett", "コアルヒー"],
    "SWANNA": ["Swanna", "スワンナ"],
    "VANILLITE": ["Vanillite", "バニプッチ"],
    "VANILLISH": ["Vanillish", "バニリッチ"],
    "VANILLUXE": ["Vanilluxe", "バイバニラ"],
    "DEERLING": ["Deerling", "シキジカ"],
    "SAWSBUCK": ["Sawsbuck", "メブキジカ"],
    "EMOLGA": ["Emolga", "エモンガ"],
    "KARRABLAST": ["Karrablast", "カブルモ"],
    "ESCAVALIER": ["Escavalier", "シュバルゴ"],
    "FOONGUS": ["Foongus", "タマゲタケ"],
    "AMOONGUSS": ["Amoonguss", "モロバレル"],
    "FRILLISH": ["Frillish", "プルリル"],
    "JELLICENT": ["Jellicent", "ブルンゲル"],
    "ALOMOMOLA": ["Alomomola", "ママンボウ"],
    "JOLTIK": ["Joltik", "バチュル"],
    "GALVANTULA": ["Galvantula", "デンチュラ"],
    "FERROSEED": ["Ferroseed", "テッシード"],
    "FERROTHORN": ["Ferrothorn", "ナットレイ"],
    "KLINK": ["Klink", "ギアル"],
    "KLANG": ["Klang", "ギギアル"],
    "KLINKLANG": ["Klinklang", "ギギギアル"],
    "TYNAMO": ["Tynamo", "テッシード"],
    "EELEKTRIK": ["Eelektrik", "シビビール"],
    "EELEKTROSS": ["Eelektross", "シビルドン"],
    "ELGYEM": ["Elgyem", "リグレー"],
    "BEHEEYEM": ["Beheeyem", "オーベム"],
    "LITWICK": ["Litwick", "ヒトモシ"],
    "LAMPENT": ["Lampent", "ランプラー"],
    "AXEW": ["Axew", "キバゴ"],
    "FRAXURE": ["Fraxure", "オノンド"],
    "HAXORUS": ["Haxorus", "オノノクス"],
    "CUBCHOO": ["Cubchoo", "クマシュン"],
    "BEARTIC": ["Beartic", "ツンベアー"],
    "CRYOGONAL": ["Cryogonal", "フリージオ"],
    "SHELMET": ["Shelmet", "チョボマキ"],
    "ACCELGOR": ["Accelgor", "アギルダー"],
    "STUNFISK": ["Stunfisk", "マッギョ"],
    "MIENFOO": ["Mienfoo", "コジョフー"],
    "MIENSHAO": ["Mienshao", "コジョンド"],
    "DRUDDIGON": ["Druddigon", "クリムガン"],
    "GOLETT": ["Golett", "ゴビット"],
    "GOLURK": ["Golurk", "ゴルーグ"],
    "PAWNIARD": ["Pawniard", "コマタナ"],
    "BISHARP": ["Bisharp", "キリキザン"],
    "KINGAMBIT": ["Kingambit", "オーガポン"],
    "BOUFFALANT": ["Bouffalant", "バッフロン"],
    "RUFFLET": ["Rufflet", "ワシボン"],
    "BRAVIARY": ["Braviary", "ウォーグル"],
    "VULLABY": ["Vullaby", "カラカラ"],
    "MANDIBUZZ": ["Mandibuzz", "バルジーナ"],
    "HEATMOR": ["Heatmor", "クイタラン"],
    "DURANT": ["Durant", "アイアント"],
    "DEINO": ["Deino", "モノズ"],
    "ZWEILOUS": ["Zweilous", "ジヘッド"],
    "LARVESTA": ["Larvesta", "メラルバ"],
    "COBALION": ["Cobalion", "コバルオン"],
    "TERRAKION": ["Terrakion", "テラキオン"],
    "VIRIZION": ["Virizion", "ビリジオン"],
    "TORNADUS": ["Tornadus", "トルネロス"],
    "THUNDURUS": ["Thundurus", "ボルトロス"],
    "LANDORUS": ["Landorus", "ランドロス"],
    "ENAMORUS": ["Enamorus", "ラブトロス"],
    "KELDEO": ["Keldeo", "ケルディオ"],

    # 第6世代（未登録分）
    "CHESPIN": ["Chespin", "ハリマロン"],
    "QUILLADIN": ["Quilladin", "ハリボーグ"],
    "FENNEKIN": ["Fennekin", "フォッコ"],
    "BRAIXEN": ["Braixen", "テールナー"],
    "FROAKIE": ["Froakie", "ケロマツ"],
    "FROGADIER": ["Frogadier", "ゲコガシラ"],
    "BUNNELBY": ["Bunnelby", "ホルビー"],
    "DIGGERSBY": ["Diggersby", "ホルード"],
    "FLETCHLING": ["Fletchling", "ヤヤコマ"],
    "FLETCHINDER": ["Fletchinder", "ヒノヤコマ"],
    "SCATTERBUG": ["Scatterbug", "コフキムシ"],
    "SPEWPA": ["Spewpa", "コフーライ"],
    "VIVILLON": ["Vivillon", "ビビヨン"],
    "LITLEO": ["Litleo", "シシコ"],
    "PYROAR": ["Pyroar", "カエンジシ"],
    "FLABEBE": ["Flabébé", "フラベベ"],
    "FLOETTE": ["Floette", "フラエッテ"],
    "FLORGES": ["Florges", "フラージェス"],
    "SKIDDO": ["Skiddo", "メェークル"],
    "GOGOAT": ["Gogoat", "ゴーゴート"],
    "PANCHAM": ["Pancham", "ヤンチャム"],
    "PANGORO": ["Pangoro", "ゴロンダ"],
    "FURFROU": ["Furfrou", "トリミアン"],
    "ESPURR": ["Espurr", "ニャスパー"],
    "MEOWSTIC": ["Meowstic", "ニャオニクス"],
    "HONEDGE": ["Honedge", "ヒトツキ"],
    "DOUBLADE": ["Doublade", "ニダンギル"],
    "SPRITZEE": ["Spritzee", "シュシュプ"],
    "AROMATISSE": ["Aromatisse", "フレフワン"],
    "SWIRLIX": ["Swirlix", "ペロッパフ"],
    "SLURPUFF": ["Slurpuff", "ペロリーム"],
    "INKAY": ["Inkay", "マーイーカ"],
    "MALAMAR": ["Malamar", "カラマネロ"],
    "BINACLE": ["Binacle", "カメテテ"],
    "BARBARACLE": ["Barbaracle", "ガメノデス"],
    "SKRELP": ["Skrelp", "クズモー"],
    "DRAGALGE": ["Dragalge", "ドラミドロ"],
    "CLAUNCHER": ["Clauncher", "ウデッポウ"],
    "CLAWITZER": ["Clawitzer", "ブロスター"],
    "HELIOPTILE": ["Helioptile", "エリキテル"],
    "HELIOLISK": ["Heliolisk", "エレザード"],
    "AMAURA": ["Amaura", "アマルス"],
    "AURORUS": ["Aurorus", "アマルルガ"],
    "CARBINK": ["Carbink", "メレシー"],
    "GOOMY": ["Goomy", "ヌメラ"],
    "SLIGGOO": ["Sliggoo", "ヌメイル"],
    "KLEFKI": ["Klefki", "クレッフィ"],
    "PHANTUMP": ["Phantump", "ボクレー"],
    "TREVENANT": ["Trevenant", "オーロット"],
    "PUMPKABOO": ["Pumpkaboo", "バケッチャ"],
    "GOURGEIST": ["Gourgeist", "パンプジン"],
    "BERGMITE": ["Bergmite", "カチコール"],
    "AVALUGG": ["Avalugg", "クレベース"],
    "PHANTUMP": ["Phantump", "ボクレー"],
    "ZYGARDE": ["Zygarde", "ジガルデ"],
    "DIANCIE": ["Diancie", "ディアンシー"],
    "HOOPA": ["Hoopa", "フーパ"],
    "VOLCANION": ["Volcanion", "ボルケニオン"],

    # 第7世代（未登録分）
    "ROWLET": ["Rowlet", "モクロー"],
    "DARTRIX": ["Dartrix", "フクスロー"],
    "LITTEN": ["Litten", "ニャビー"],
    "TORRACAT": ["Torracat", "ニャヒート"],
    "POPPLIO": ["Popplio", "アシマリ"],
    "BRIONNE": ["Brionne", "オシャマリ"],
    "PIKIPEK": ["Pikipek", "ツツケラ"],
    "TRUMBEAK": ["Trumbeak", "ケララッパ"],
    "TOUCANNON": ["Toucannon", "ドデカバシ"],
    "YUNGOOS": ["Yungoos", "ヤングース"],
    "GUMSHOOS": ["Gumshoos", "デカグース"],
    "GRUBBIN": ["Grubbin", "アゴジムシ"],
    "CHARJABUG": ["Charjabug", "デンヂムシ"],
    "VIKAVOLT": ["Vikavolt", "クワガノン"],
    "CRABRAWLER": ["Crabrawler", "マケンカニ"],
    "CRABOMINABLE": ["Crabominable", "ケケンカニ"],
    "CUTIEFLY": ["Cutiefly", "アブリー"],
    "RIBOMBEE": ["Ribombee", "アブリボン"],
    "ROCKRUFF": ["Rockruff", "イワンコ"],
    "LYCANROC": ["Lycanroc", "ルガルガン"],
    "DEWPIDER": ["Dewpider", "シズクモ"],
    "ARAQUANID": ["Araquanid", "オニシズクモ"],
    "FOMANTIS": ["Fomantis", "カリキリ"],
    "LURANTIS": ["Lurantis", "ラランテス"],
    "MORELULL": ["Morelull", "ネマシュ"],
    "SHIINOTIC": ["Shiinotic", "マシェード"],
    "SALANDIT": ["Salandit", "ヤトウモリ"],
    "SALAZZLE": ["Salazzle", "エンニュート"],
    "STUFFUL": ["Stufful", "ヌイコグマ"],
    "BOUNSWEET": ["Bounsweet", "アマカジ"],
    "STEENEE": ["Steenee", "アママイコ"],
    "TSAREENA": ["Tsareena", "アマージョ"],
    "COMFEY": ["Comfey", "キュワワー"],
    "ORANGURU": ["Oranguru", "ナッシーウラ"],
    "PASSIMIAN": ["Passimian", "ナゲツケサル"],
    "WIMPOD": ["Wimpod", "コソクムシ"],
    "GOLISOPOD": ["Golisopod", "グソクムシャ"],
    "SANDYGAST": ["Sandygast", "スナバァ"],
    "PALOSSAND": ["Palossand", "シロデスナ"],
    "TYPE NULL": ["Type: Null", "タイプ：ヌル"],
    "SILVALLY": ["Silvally", "シルヴァディ"],
    "MINIOR": ["Minior", "メテノ"],
    "KOMALA": ["Komala", "ネッコアラ"],
    "TURTONATOR": ["Turtonator", "バクガメス"],
    "TOGEDEMARU": ["Togedemaru", "トゲデマル"],
    "DRAMPA": ["Drampa", "ジジーロン"],
    "DHELMISE": ["Dhelmise", "ダダリン"],
    "JANGMOO": ["Jangmo-o", "ジャラコ"],
    "HAKAMOO": ["Hakamo-o", "ジャランゴ"],
    "TAPUKOKO": ["Tapu Koko", "カプ・コケコ"],
    "TAPULELE": ["Tapu Lele", "カプ・テテフ"],
    "TAPUBULU": ["Tapu Bulu", "カプ・ブルル"],
    "TAPUFINI": ["Tapu Fini", "カプ・レヒレ"],
    "COSMOG": ["Cosmog", "コスモッグ"],
    "COSMOEM": ["Cosmoem", "コスモウム"],
    "SOLGALEO": ["Solgaleo", "ソルガレオ"],
    "LUNALA": ["Lunala", "ルナアーラ"],
    "NIHILEGO": ["Nihilego", "ニルギリ"],
    "BUZZWOLE": ["Buzzwole", "マッシブーン"],
    "PHEROMOSA": ["Pheromosa", "フェローチェ"],
    "XURKITREE": ["Xurkitree", "デンジュモク"],
    "CELESTEELA": ["Celesteela", "テッカグヤ"],
    "KARTANA": ["Kartana", "カミツルギ"],
    "GUZZLORD": ["Guzzlord", "アクジキング"],
    "POIPOLE": ["Poipole", "ベベノム"],
    "NAGANADEL": ["Naganadel", "アーゴヨン"],
    "STAKATAKA": ["Stakataka", "ツンデツンデ"],
    "BLACEPHALON": ["Blacephalon", "ズガドーン"],
    "NECROZMA": ["Necrozma", "ネクロズマ"],
    "MARSHADOW": ["Marshadow", "マーシャドー"],
    "ZERAORA": ["Zeraora", "ゼラオラ"],
    "MAGEARNA": ["Magearna", "マギアナ"],
    "MELTAN": ["Meltan", "メルタン"],
    "MELMETAL": ["Melmetal", "メルメタル"],

    # 第8世代（未登録分）
    "GROOKEY": ["Grookey", "サルノリ"],
    "THWACKEY": ["Thwackey", "バチンキー"],
    "SCORBUNNY": ["Scorbunny", "ヒバニー"],
    "RABOOT": ["Raboot", "ラビフット"],
    "SOBBLE": ["Sobble", "メッソン"],
    "DRIZZILE": ["Drizzile", "ジメレオン"],
    "SKWOVET": ["Skwovet", "ホシガリス"],
    "GREEDENT": ["Greedent", "ヨクバリス"],
    "ROOKIDEE": ["Rookidee", "ルチャブル"],
    "CORVISQUIRE": ["Corvisquire", "コルビョウ"],
    "CORVIKNIGHT": ["Corviknight", "アーマーガア"],
    "BLIPBUG": ["Blipbug", "サッチムシ"],
    "DOTTLER": ["Dottler", "レドームシ"],
    "ORBEETLE": ["Orbeetle", "イオルブ"],
    "NICKIT": ["Nickit", "クスネ"],
    "THIEVUL": ["Thievul", "フォクスライ"],
    "GOSSIFLEUR": ["Gossifleur", "ヒメンカ"],
    "ELDEGOSS": ["Eldegoss", "ワタシラガ"],
    "WOOLOO": ["Wooloo", "ウールー"],
    "DUBWOOL": ["Dubwool", "ダブルウール"],
    "CHEWTLE": ["Chewtle", "カムカメ"],
    "DREDNAW": ["Drednaw", "カジリガメ"],
    "YAMPER": ["Yamper", "ワンパチ"],
    "BOLTUND": ["Boltund", "パルスワン"],
    "ROLYCOLY": ["Rolycoly", "タンドン"],
    "CARKOL": ["Carkol", "トロッゴン"],
    "COALOSSAL": ["Coalossal", "セキタンザン"],
    "APPLIN": ["Applin", "パパッチ"],
    "FLAPPLE": ["Flapple", "アップリュー"],
    "APPLETUN": ["Appletun", "タルップル"],
    "SILICOBRA": ["Silicobra", "サダイジャ"],
    "SANDACONDA": ["Sandaconda", "サダイジャ"],
    "CRAMORANT": ["Cramorant", "ウッウ"],
    "ARROKUDA": ["Arrokuda", "サシカマス"],
    "BARRASKEWDA": ["Barraskewda", "カマスジョー"],
    "TOXEL": ["Toxel", "エレズン"],
    "SIZZLIPEDE": ["Sizzlipede", "ヤクデ"],
    "CENTISKORCH": ["Centiskorch", "マルヤクデ"],
    "CLOBBOPUS": ["Clobbopus", "タコワシ"],
    "GRAPPLOCT": ["Grapploct", "オトスパス"],
    "SINISTEA": ["Sinistea", "ヤバチャ"],
    "POLTEAGEIST": ["Polteageist", "ポットデス"],
    "HATENNA": ["Hatenna", "ミブリム"],
    "HATTREM": ["Hattrem", "テブリム"],
    "HATTERENE": ["Hatterene", "ブリムオン"],
    "IMPIDIMP": ["Impidimp", "ベロバー"],
    "MORGREM": ["Morgrem", "ギモー"],
    "MILCERY": ["Milcery", "マホミル"],
    "ALCREMIE": ["Alcremie", "マホイップ"],
    "FALINKS": ["Falinks", "タイレーツ"],
    "PINCURCHIN": ["Pincurchin", "バチンウニ"],
    "SNOM": ["Snom", "ユキハミ"],
    "FROSMOTH": ["Frosmoth", "モスノウ"],
    "STONJOURNER": ["Stonjourner", "イシヘンジン"],
    "EISCUE": ["Eiscue", "コオリッポ"],
    "INDEEDEE": ["Indeedee", "イエッサン"],
    "MORPEKO": ["Morpeko", "モルペコ"],
    "CUFANT": ["Cufant", "ゾウドウ"],
    "COPPERAJAH": ["Copperajah", "ダイオウドウ"],
    "DRACOZOLT": ["Dracozolt", "パッチラゴン"],
    "ARCTOZOLT": ["Arctozolt", "パッチルドン"],
    "DRACOVISH": ["Dracovish", "ウオチルドン"],
    "ARCTOVISH": ["Arctovish", "ウオノラゴン"],
    "DREEPY": ["Dreepy", "ドラメシヤ"],
    "DRAKLOAK": ["Drakloak", "ドロンチ"],
    "KUBFU": ["Kubfu", "ダクマ"],
    "ZARUDE": ["Zarude", "ザルード"],
    "GLASTRIER": ["Glastrier", "ブリザポス"],
    "SPECTRIER": ["Spectrier", "レイスポス"],

    # 第9世代（未登録分）
    "LECHONK": ["Lechonk", "マメバター"],
    "OINKOLOGNE": ["Oinkologne", "ベロリンガ"],
    "TAROUNTULA": ["Tarountula", "タリポット"],
    "SPIDOPS": ["Spidops", "ネマクマ"],
    "NYMBLE": ["Nymble", "ハネッコ"],
    "LOKIX": ["Lokix", "エレズン"],
    "PAWMI": ["Pawmi", "パフュートン"],
    "PAWMO": ["Pawmo", "パフュートン"],
    "PAWMOT": ["Pawmot", "パフュートン"],
    "TANDEMAUS": ["Tandemaus", "イキリンコ"],
    "MAUSHOLD": ["Maushold", "イキリンコ"],
    "FIDOUGH": ["Fidough", "パモ"],
    "DACHSBUN": ["Dachsbun", "パモット"],
    "SMOLIV": ["Smoliv", "タマンチュラ"],
    "DOLLIV": ["Dolliv", "スピンロー"],
    "ARBOLIVA": ["Arboliva", "オリーニャ"],
    "SQUAWKABILLY": ["Squawkabilly", "イキリンコ"],
    "NACLI": ["Nacli", "ガケガニ"],
    "NACLSTACK": ["Naclstack", "ウミディグダ"],
    "GARGANACL": ["Garganacl", "ウミトリオ"],
    "CHARCADET": ["Charcadet", "カルボウ"],
    "ARMAROUGE": ["Armarouge", "グレンアルマ"],
    "CERULEDGE": ["Ceruledge", "ソウブレイズ"],
    "TADBULB": ["Tadbulb", "ズピカ"],
    "BELLIBOLT": ["Bellibolt", "ハラバリー"],
    "WATTREL": ["Wattrel", "カイデン"],
    "KILOWATTREL": ["Kilowattrel", "タイカイデン"],
    "MASCHIFF": ["Maschiff", "マフォクシー"],
    "MABOSSTIFF": ["Mabosstiff", "ドオー"],
    "SHROODLE": ["Shroodle", "ノノクラゲ"],
    "GRAFAIAI": ["Grafaiai", "ドオー"],
    "BRAMBLIN": ["Bramblin", "タマザラシ"],
    "BRAMBLEGHAST": ["Brambleghast", "ソウブレイズ"],
    "TOEDSCOOL": ["Toedscool", "タルップル"],
    "TOEDSCRUEL": ["Toedscruel", "アップリュー"],
    "KLAWF": ["Klawf", "ガケガニ"],
    "CAPSAKID": ["Capsakid", "カプサイジ"],
    "SCOVILLAIN": ["Scovillain", "スコヴィラン"],
    "RELLOR": ["Rellor", "コロモリ"],
    "RABSCA": ["Rabsca", "ランクルス"],
    "FLITTLE": ["Flittle", "ヒラヒナ"],
    "ESPATHRA": ["Espathra", "クエスパトラ"],
    "TINKATINK": ["Tinkatink", "デカヌチャン"],
    "TINKATUFF": ["Tinkatuff", "デカヌチャン"],
    "WIGLETT": ["Wiglett", "ウミディグダ"],
    "WUGTRIO": ["Wugtrio", "ウミトリオ"],
    "BOMBIRDIER": ["Bombirdier", "イキリンコ"],
    "FINIZEN": ["Finizen", "イルカマン"],
    "VAROOM": ["Varoom", "ジバコイル"],
    "REVAVROOM": ["Revavroom", "ジバコイル"],
    "CYCLIZAR": ["Cyclizar", "ドライドライ"],
    "ORTHWORM": ["Orthworm", "ミミズズ"],
    "GLIMMET": ["Glimmet", "キラフロル"],
    "GLIMMORA": ["Glimmora", "キラフロル"],
    "GREAVARD": ["Greavard", "ハカドッグ"],
    "HOUNDSTONE": ["Houndstone", "グレンアルマ"],
    "FLAMIGO": ["Flamigo", "フラミゴ"],
    "CETODDLE": ["Cetoddle", "ウォモン"],
    "CETITAN": ["Cetitan", "ウォモン"],
    "VELUZA": ["Veluza", "ベラカス"],
    "DONDOZO": ["Dondozo", "ヘイラッシャ"],
    "TATSUGIRI": ["Tatsugiri", "タツギリ"],
    "ANNIHILAPE": ["Annihilape", "コノヨザル"],
    "CLODSIRE": ["Clodsire", "ドオー"],
    "FARIGIRAF": ["Farigiraf", "リキキリン"],
    "DUDUNSPARCE": ["Dudunsparce", "ノコッチ"],
    "KINGAMBIT": ["Kingambit", "サーフゴー"],
    "GREAT TUSK": ["Great Tusk", "クエスパトラ"],
    "SCREAM TAIL": ["Scream Tail", "パフュートン"],
    "BRUTE BONNET": ["Brute Bonnet", "モロバレル"],
    "FLUTTER MANE": ["Flutter Mane", "ハバタクカミ"],
    "SLITHER WING": ["Slither Wing", "チヲハウハネ"],
    "SANDY SHOCKS": ["Sandy Shocks", "サケブシッポ"],
    "IRON TREADS": ["Iron Treads", "テツノワダチ"],
    "IRON BUNDLE": ["Iron Bundle", "テツノツツミ"],
    "IRON HANDS": ["Iron Hands", "テツノコブシ"],
    "IRON JUGULIS": ["Iron Jugulis", "テツノカイナ"],
    "IRON MOTH": ["Iron Moth", "テツノドクガ"],
    "IRON THORNS": ["Iron Thorns", "テツノイバラ"],
    "FRIGIBAX": ["Frigibax", "ジュラルドン"],
    "ARCTIBAX": ["Arctibax", "ジュラルドン"],
    "BAXCALIBUR": ["Baxcalibur", "バクガメス"],
    "GIMMIGHOUL": ["Gimmighoul", "コレクレー"],
    "GHOLDENGO": ["Gholdengo", "サーフゴー"],
    "WALKING WAKE": ["Walking Wake", "テツノコブシ"],
    "IRON LEAVES": ["Iron Leaves", "テツノブジン"],
    "DIPPLIN": ["Dipplin", "ドロンチ"],
    "POLTCHAGEIST": ["Poltchageist", "ポットデス"],
    "SINISTCHA": ["Sinistcha", "ヤバチャ"],
    "OKIDOGI": ["Okidogi", "イイネイヌ"],
    "MUNKIDORI": ["Munkidori", "マシマシラ"],
    "FEZANDIPITI": ["Fezandipiti", "キチキギス"],
    "OGERPON": ["Ogerpon", "オーガポン"],
    "ARCHALUDON": ["Archaludon", "ジュラルドン"],
    "HYDRAPPLE": ["Hydrapple", "ドロンチ"],
    "GOUGING FIRE": ["Gouging Fire", "ガチグマ"],
    "RAGING BOLT": ["Raging Bolt", "ライコウ"],
    "IRON BOULDER": ["Iron Boulder", "テツノカシラ"],
    "IRON CROWN": ["Iron Crown", "テツノカシラ"],
    "TERAPAGOS": ["Terapagos", "テラパゴス"],
    "PECHARUNT": ["Pecharunt", "モモワロウ"],

    # トレーナーカード
    # トレーナーカード（男性）
    "REDBLUE": ["Red", "レッド"],
    "CALEM": ["Calem", "カルム"],
    "BRENDAN": ["Brendan", "ユウキ"],
    "LUCAS": ["Lucas", "コウキ"],
    "HILBERT": ["Hilbert", "トウヤ"],
    "NATE": ["Nate", "キョウヘイ"],
    "XAVIER": ["Xavier", "ゼロ"],
    "VICTOR": ["Victor", "ユウボウ"],
    "FLORIAN": ["Florian", "フローラン"],

    # トレーナーカード（女性）
    "LEAF": ["Leaf", "リーフ"],
    "KRIS": ["Kris", "クリス"],
    "MAY": ["May", "ハルカ"],
    "DAWN": ["Dawn", "ヒカリ"],
    "HILDA": ["Hilda", "トウコ"],
    "ROSA": ["Rosa", "メイ"],
    "SERENA": ["Serena", "セレナ"],
    "SHAUNA": ["Shauna", "サナ"],
    "SELENE": ["Selene", "みずき"],
    "GLORIA": ["Gloria", "ユウリ"],
    "JULIANA": ["Juliana", "ジュリア"],

    # ジムリーダー・四天王・チャンピオン（カントー）
    "BROCK": ["Brock", "タケシ"],
    "MISTY": ["Misty", "カスミ"],
    "SURGE": ["Lt. Surge", "マチス"],
    "ERIKA": ["Erika", "エリカ"],
    "KOGA": ["Koga", "キョウ"],
    "SABRINA": ["Sabrina", "ナツメ"],
    "BLAINE": ["Blaine", "カツラ"],
    "GIOVANNI": ["Giovanni", "サカキ"],
    "LORELEI": ["Lorelei", "カンナ"],
    "BRUNO": ["Bruno", "シバ"],
    "AGATHA": ["Agatha", "キクコ"],
    "LANCE": ["Lance", "ワタル"],
    "BLUE": ["Blue", "グリーン"],

    # ジムリーダー・四天王・チャンピオン（ジョウト）
    "FALKNER": ["Falkner", "ハヤト"],
    "BUGSY": ["Bugsy", "ツクシ"],
    "WHITNEY": ["Whitney", "アカネ"],
    "MORTY": ["Morty", "マツバ"],
    "CHUCK": ["Chuck", "シジマ"],
    "JASMINE": ["Jasmine", "ミカン"],
    "PRYCE": ["Pryce", "ヤナギ"],
    "CLAIR": ["Clair", "イブキ"],
    "WILL": ["Will", "イツキ"],
    "KAREN": ["Karen", "カリン"],

    # ジムリーダー・四天王・チャンピオン（ホウエン）
    "ROXANNE": ["Roxanne", "ツツジ"],
    "BRAWLY": ["Brawly", "トウキ"],
    "WATTSON": ["Wattson", "テッセン"],
    "FLANNERY": ["Flannery", "アスナ"],
    "NORMAN": ["Norman", "センリ"],
    "WINONA": ["Winona", "ナギ"],
    "TATE": ["Tate", "フウ"],
    "LIZA": ["Liza", "ラン"],
    "WALLACE": ["Wallace", "ミクリ"],
    "SIDNEY": ["Sidney", "カゲツ"],
    "PHOEBE": ["Phoebe", "フヨウ"],
    "GLACIA": ["Glacia", "プリム"],
    "DRAKE": ["Drake", "ゲンジ"],
    "STEVEN": ["Steven", "ダイゴ"],

    # ジムリーダー・四天王・チャンピオン（シンオウ）
    "ROARK": ["Roark", "ヒョウタ"],
    "GARDENIA": ["Gardenia", "ナタネ"],
    "MAYLENE": ["Maylene", "スモモ"],
    "CRASHER": ["Crasher Wake", "マキシ"],
    "FANTINA": ["Fantina", "メリッサ"],
    "BYRON": ["Byron", "トウガン"],
    "CANDICE": ["Candice", "スズナ"],
    "VOLKNER": ["Volkner", "デンジ"],
    "AARON": ["Aaron", "リョウ"],
    "BERTHA": ["Bertha", "キクノ"],
    "FLINT": ["Flint", "オーバ"],
    "LUCIAN": ["Lucian", "ゴヨウ"],
    "CYNTHIA": ["Cynthia", "シロナ"],

    # ジムリーダー・四天王・チャンピオン（イッシュ）
    "CHILI": ["Chili", "ポッド"],
    "CRESS": ["Cress", "コーン"],
    "CILAN": ["Cilan", "デント"],
    "LENORA": ["Lenora", "アロエ"],
    "BURGH": ["Burgh", "アーティ"],
    "ELESA": ["Elesa", "カミツレ"],
    "CLAY": ["Clay", "ヤーコン"],
    "SKYLA": ["Skyla", "フウロ"],
    "BRYCEN": ["Brycen", "ハチク"],
    "DRAYDEN": ["Drayden", "シャガ"],
    "SHAUNTAL": ["Shauntal", "シキミ"],
    "MARSHAL": ["Marshal", "コバルオン"],
    "GRIMSLEY": ["Grimsley", "ギーマ"],
    "CAITLIN": ["Caitlin", "カトレア"],
    "IRIS": ["Iris", "アイリス"],
    "ALDER": ["Alder", "アデク"],

    # ジムリーダー・四天王・チャンピオン（カロス）
    "VIOLA": ["Viola", "シトロン"],
    "GRANT": ["Grant", "ザクロ"],
    "KORRINA": ["Korrina", "コルニ"],
    "RAMOS": ["Ramos", "フクジ"],
    "CLEMONT": ["Clemont", "シトロン"],
    "VALERIE": ["Valerie", "マーシュ"],
    "OLYMPIA": ["Olympia", "ゴジカ"],
    "WULFRIC": ["Wulfric", "ウルップ"],
    "MALVA": ["Malva", "パキラ"],
    "SIEBOLD": ["Siebold", "ズミ"],
    "WIKSTROM": ["Wikstrom", "ドラサナ"],
    "DRASNA": ["Drasna", "ドラサナ"],
    "DIANTHA": ["Diantha", "カルネ"],

    # ジムリーダー・四天王・チャンピオン（アローラ）
    "ILIMA": ["Ilima", "マオ"],
    "LANA": ["Lana", "スイレン"],
    "KIAWE": ["Kiawe", "カキ"],
    "MALLOW": ["Mallow", "マオ"],
    "SOPHOCLES": ["Sophocles", "マーマネ"],
    "ACEROLA": ["Acerola", "アセロラ"],
    "MINA": ["Mina", "マツリカ"],
    "NANU": ["Nanu", "ククイ"],
    "HAPU": ["Hapu", "ハプウ"],
    "MOLAYNE": ["Molayne", "モラペ"],
    "OLIVIA": ["Olivia", "ライチ"],
    "KAHILI": ["Kahili", "カヒリ"],
    "KUKUI": ["Kukui", "ククイ"],
    "LUSAMINE": ["Lusamine", "ルザミーネ"],
    "GLADION": ["Gladion", "グラジオ"],
    "LILLIE": ["Lillie", "リーリエ"],
    "HALA": ["Hala", "ハラ"],

    # ジムリーダー・四天王・チャンピオン（ガラル）
    "MILO": ["Milo", "ヤロー"],
    "NESSA": ["Nessa", "ルリナ"],
    "KABU": ["Kabu", "カブ"],
    "BEA": ["Bea", "サイトウ"],
    "ALLISTER": ["Allister", "オニオン"],
    "OPAL": ["Opal", "ポプラ"],
    "BEDE": ["Bede", "ビート"],
    "GORDIE": ["Gordie", "マサコ"],
    "MELONY": ["Melony", "メロン"],
    "PIERS": ["Piers", "ネズ"],
    "MARNIE": ["Marnie", "マリィ"],
    "RAIHAN": ["Raihan", "キバナ"],
    "LEON": ["Leon", "ダンデ"],
    "HOP": ["Hop", "ホップ"],
    "SONIA": ["Sonia", "ソニア"],
    "ROSE": ["Rose", "ローズ"],

    # ジムリーダー・四天王・チャンピオン（パルデア）
    "KATY": ["Katy", "カエデ"],
    "BRASSIUS": ["Brassius", "コルサ"],
    "IONO": ["Iono", "アオキ"],
    "KOFU": ["Kofu", "ハイダイ"],
    "LARRY": ["Larry", "アオキ"],
    "RYME": ["Ryme", "リップ"],
    "TULIP": ["Tulip", "ポピー"],
    "GRUSHA": ["Grusha", "グルーシャ"],
    "RIKA": ["Rika", "チリ"],
    "POPPY": ["Poppy", "ポピー"],
    "HASSEL": ["Hassel", "ハッサク"],
    "CRISPIN": ["Crispin", "アカマツ"],
    "AMARYS": ["Amarys", "アマリリス"],
    "LACEY": ["Lacey", "タロ"],
    "DRAYTON": ["Drayton", "カキツバタ"],
    "NEMONA": ["Nemona", "ネモ"],
    "PENNY": ["Penny", "ペパー"],
    "ARVEN": ["Arven", "アルベル"],

    # 悪の組織
    "JESSIE": ["Jessie", "ムサシ"],
    "JAMES": ["James", "コジロウ"],
    "ARCHER": ["Archer", "アポロ"],
    "ARIANA": ["Ariana", "アリアナ"],
    "PROTON": ["Proton", "ランス"],
    "PETREL": ["Petrel", "べと"],
    "MAXIE": ["Maxie", "マツブサ"],
    "ARCHIE": ["Archie", "アオギリ"],
    "CYRUS": ["Cyrus", "アカギ"],
    "GHETSIS": ["Ghetsis", "ゲーチス"],
    "LYSANDRE": ["Lysandre", "フラダリ"],
    "GUZMA": ["Guzma", "グズマ"],
    "PLUMERIA": ["Plumeria", "プルメリ"],
    "MACRO": ["Macro Cosmos", "マクロコスモス"],
    "OLEANA": ["Oleana", "オリーヴ"],

    # 博士・助手
    "PROFESSOR OAK": ["Professor Oak", "オーキド博士"],
    "ELM": ["Professor Elm", "ウツギ博士"],
    "BIRCH": ["Professor Birch", "オダマキ博士"],
    "ROWAN": ["Professor Rowan", "ナナカマド博士"],
    "JUNIPER": ["Professor Juniper", "アララギ博士"],
    "SYCAMORE": ["Professor Sycamore", "プラターヌ博士"],
    "KUKUI": ["Professor Kukui", "ククイ博士"],
    "MAGNOLIA": ["Professor Magnolia", "マグノリア博士"],
    "SONIA": ["Sonia", "ソニア"],
    "WILLOW": ["Professor Willow", "ウィロー博士"],

    # その他有名キャラ
    "BILL": ["Bill", "マサキ"],
    "MISTY": ["Misty", "カスミ"],
    "TOBIAS": ["Tobias", "タクト"],
    "PIKACHU": ["Pikachu", "ピカチュウ"],
    "GOH": ["Goh", "ゴウ"],
    "BROCK": ["Brock", "タケシ"],
    "TRACEY": ["Tracey", "ケンジ"],
    "CLEMONT": ["Clemont", "シトロン"],
    "BONNIE": ["Bonnie", "ユリーカ"],
    "LANA": ["Lana", "スイレン"],
    "KIAWE": ["Kiawe", "カキ"],
    "MALLOW": ["Mallow", "マオ"],
    "SOPHOCLES": ["Sophocles", "マーマネ"],
    "LILLIE": ["Lillie", "リーリエ"],
    "CHLOE": ["Chloe", "コハル"],
    # レジェンズZ-A
    "CANARI": ["Canari", "カナリィ"],
    "CORBEAU": ["Corbeau", "カラスバ"],
    "GWYNN": ["Gwynn", "ムク"],
    "URBAIN": ["Urbain", "ガイ"],
    "TAUNIE": ["Taunie", "タウニー"],
    "LIDA": ["Lida", "デウロ"],
    "NAVEEN": ["Naveen", "ピュール"],
    "JETT": ["Jett", "ジェット"],
    "VINNIE": ["Vinnie", "ヴィーニー"],
    "IVOR": ["Ivor", "シロー"],
    "JACINTHE": ["Jacinthe", "ユカリ"],
    "LEBANNE": ["Lebanne", "ジプソ"],
}

def get_tags(title):
    title_clean = title.replace(" ", "").replace("-", "").replace("'", "").upper()

    
    # グレードタグを追加
    grade_tags = []
    if "PSA10" in title_clean:
        grade_tags.append("PSA10")
    elif "PSA9" in title_clean:
        grade_tags.append("PSA9")
    elif "PSA8" in title_clean:
        grade_tags.append("PSA8以下")
    elif "PSA7" in title_clean:
        grade_tags.append("PSA8以下")
    elif "PSA6" in title_clean:
        grade_tags.append("PSA8以下")
    elif "PSA5" in title_clean:
        grade_tags.append("PSA8以下")
    elif "BGS" in title_clean:
        grade_tags.append("その他グレード")
    elif "CGC" in title_clean:
        grade_tags.append("その他グレード")
    elif "PSA" in title_clean:
        grade_tags.append("PSA(グレード不明)")
    else:
        grade_tags.append("素体")
    
    tags = []
    matched_keys = []

    # 〇〇の〇〇カードのタグ付け
    for jp_name, en_name in TRAINER_POKEMON_DICT.items():
        en_clean = en_name.replace(" ", "").replace("-", "").replace("'", "").upper()
        if en_clean in title_clean:
            tags.append(jp_name)
            break

    # 男女トレーナー判定（tagsの定義後に置く）
    MALE_TRAINERS = [
        "BROCK", "LTSURGE", "KOGA", "BLAINE", "GIOVANNI", "BRUNO", "LANCE", "BLUE",
        "FALKNER", "BUGSY", "MORTY", "CHUCK", "PRYCE", "WILL", "BRAWLY", "WATTSON",
        "NORMAN", "WALLACE", "SIDNEY", "DRAKE", "STEVEN", "ROARK", "CRASHERWAKE",
        "BYRON", "VOLKNER", "AARON", "FLINT", "LUCIAN", "CHILI", "CRESS", "CILAN",
        "BURGH", "CLAY", "BRYCEN", "DRAYDEN", "GRIMSLEY", "ALDER",
        "GRANT", "RAMOS", "CLEMONT", "WULFRIC", "SIEBOLD", "WIKSTROM", "ILIMA",
        "KIAWE", "SOPHOCLES", "NANU", "KUKUI", "GLADION", "HALA", "MILO", "KABU",
        "ALLISTER", "BEDE", "GORDIE", "PIERS", "RAIHAN", "LEON", "HOP", "BRASSIUS",
        "KOFU", "LARRY", "GRUSHA", "HASSEL", "ARVEN", "JAMES", "ARCHER", "PROTON",
        "PETREL", "MAXIE", "ARCHIE", "CYRUS", "GHETSIS", "LYSANDRE", "GUZMA",
        "PROFESSOROAK", "URBAIN", "NAVEEN", "JETT", "VINNIE", "IVOR", "CORBEAU"
    ]

    FEMALE_TRAINERS = [
        "MISTY", "ERIKA", "SABRINA", "LORELEI", "AGATHA", "WHITNEY", "JASMINE",
        "CLAIR", "KAREN", "ROXANNE", "FLANNERY", "WINONA", "PHOEBE", "GLACIA",
        "GARDENIA", "MAYLENE", "FANTINA", "CANDICE", "CYNTHIA", "LENORA", "ELESA",
        "SKYLA", "SHAUNTAL", "CAITLIN", "IRIS", "VIOLA", "KORRINA", "VALERIE",
        "OLYMPIA", "MALVA", "DRASNA", "DIANTHA", "LANA", "MALLOW", "ACEROLA",
        "MINA", "HAPU", "OLIVIA", "KAHILI", "LUSAMINE", "LILLIE", "NESSA", "BEA",
        "OPAL", "MELONY", "MARNIE", "SONIA", "KATY", "IONO", "RYME", "TULIP",
        "RIKA", "POPPY", "NEMONA", "PENNY", "JESSIE", "ARIANA", "PLUMERIA",
        "OLEANA", "DAWN", "MAY", "SERENA", "LEAF", "KRIS", "HILDA", "ROSA",
        "GLORIA", "JULIANA", "CHLOE", "TAUNIE", "LIDA", "JACINTHE", "GWYNN",
        "LEBANNE", "CANARI", "ASUNA",
    ]

    
    
    for key, names in POKEMON_TAG_DICT.items():
        key_clean = key.replace(" ", "").replace("-", "").upper()
        if key_clean in title_clean:
            already_matched = False
            for matched in matched_keys:
                if key_clean in matched or matched in key_clean:
                    if len(matched) > len(key_clean):
                        already_matched = True
                        break
            if not already_matched:
                tags.extend(names)
                matched_keys.append(key_clean)
    # プロモカードの検出
    promo_keywords = ["PROMO", "STICKER", "FANFARE", "MCDONALD", "INFLUENCER"]
    for keyword in promo_keywords:
        if keyword in title_clean:
            if "プロモ" not in tags:
                tags.append("プロモ")
            break
    if not tags:
        tags.append("その他")
    tags = grade_tags + tags

    import re
    title_upper = title.upper()

    # ポケモン名リスト（トレーナー名を除いた純粋なポケモン名）
    POKEMON_NAMES_ONLY = [
        "Bulbasaur", "フシギダネ",
"Ivysaur", "フシギソウ",
"Venusaur", "フシギバナ",
"Charmander", "ヒトカゲ",
"Charmeleon", "リザード",
"Charizard", "リザードン",
"Squirtle", "ゼニガメ",
"Wartortle", "カメール",
"Blastoise", "カメックス",
"Caterpie", "キャタピー",
"Metapod", "トランセル",
"Butterfree", "バタフリー",
"Weedle", "ビードル",
"Kakuna", "コクーン",
"Beedrill", "スピアー",
"Pidgey", "ポッポ",
"Pidgeotto", "ピジョン",
"Pidgeot", "ピジョット",
"Rattata", "コラッタ",
"Raticate", "ラッタ",
"Spearow", "オニスズメ",
"Fearow", "オニドリル",
"Ekans", "アーボ",
"Arbok", "アーボック",
"Pikachu", "ピカチュウ",
"Raichu", "ライチュウ",
"Sandshrew", "サンド",
"Sandslash", "サンドパン",
"Nidoran♀", "ニドラン♀",
"Nidorina", "ニドリーナ",
"Nidoqueen", "ニドクイン",
"Nidoran♂", "ニドラン♂",
"Nidorino", "ニドリーノ",
"Nidoking", "ニドキング",
"Clefairy", "ピッピ",
"Clefable", "ピクシー",
"Vulpix", "ロコン",
"Ninetales", "キュウコン",
"Jigglypuff", "プリン",
"Wigglytuff", "プクリン",
"Zubat", "ズバット",
"Golbat", "ゴルバット",
"Oddish", "ナゾノクサ",
"Gloom", "クサイハナ",
"Vileplume", "ラフレシア",
"Paras", "パラス",
"Parasect", "パラセクト",
"Venonat", "コンパン",
"Venomoth", "モルフォン",
"Diglett", "ディグダ",
"Dugtrio", "ダグトリオ",
"Meowth", "ニャース",
"Persian", "ペルシアン",
"Psyduck", "コダック",
"Golduck", "ゴルダック",
"Mankey", "マンキー",
"Primeape", "オコリザル",
"Growlithe", "ガーディ",
"Arcanine", "ウインディ",
"Poliwag", "ニョロモ",
"Poliwhirl", "ニョロゾ",
"Poliwrath", "ニョロボン",
"Abra", "ケーシィ",
"Kadabra", "ユンゲラー",
"Alakazam", "フーディン",
"Machop", "ワンリキー",
"Machoke", "ゴーリキー",
"Machamp", "カイリキー",
"Bellsprout", "マダツボミ",
"Weepinbell", "ウツドン",
"Victreebel", "ウツボット",
"Tentacool", "メノクラゲ",
"Tentacruel", "ドククラゲ",
"Geodude", "イシツブテ",
"Graveler", "ゴローン",
"Golem", "ゴローニャ",
"Ponyta", "ポニータ",
"Rapidash", "ギャロップ",
"Slowpoke", "ヤドン",
"Slowbro", "ヤドラン",
"Magnemite", "コイル",
"Magneton", "レアコイル",
"Farfetch'd", "カモネギ",
"Doduo", "ドードー",
"Dodrio", "ドードリオ",
"Seel", "パウワウ",
"Dewgong", "ジュゴン",
"Grimer", "ベトベター",
"Muk", "ベトベトン",
"Shellder", "シェルダー",
"Cloyster", "パルシェン",
"Gastly", "ゴース",
"Haunter", "ゴースト",
"Gengar", "ゲンガー",
"Onix", "イワーク",
"Drowzee", "スリープ",
"Hypno", "スリーパー",
"Krabby", "クラブ",
"Kingler", "キングラー",
"Voltorb", "ビリリダマ",
"Electrode", "マルマイン",
"Exeggcute", "タマタマ",
"Exeggutor", "ナッシー",
"Cubone", "カラカラ",
"Marowak", "ガラガラ",
"Hitmonlee", "サワムラー",
"Hitmonchan", "エビワラー",
"Lickitung", "ベロリンガ",
"Koffing", "ドガース",
"Weezing", "マタドガス",
"Rhyhorn", "サイホーン",
"Rhydon", "サイドン",
"Chansey", "ラッキー",
"Tangela", "モンジャラ",
"Kangaskhan", "ガルーラ",
"Horsea", "タッツー",
"Seadra", "シードラ",
"Goldeen", "トサキント",
"Seaking", "アズマオウ",
"Staryu", "ヒトデマン",
"Starmie", "スターミー",
"Mr. Mime", "バリヤード",
"Scyther", "ストライク",
"Jynx", "ルージュラ",
"Electabuzz", "エレブー",
"Magmar", "ブーバー",
"Pinsir", "カイロス",
"Tauros", "ケンタロス",
"Magikarp", "コイキング",
"Gyarados", "ギャラドス",
"Lapras", "ラプラス",
"Ditto", "メタモン",
"Eevee", "イーブイ",
"Vaporeon", "シャワーズ",
"Jolteon", "サンダース",
"Flareon", "ブースター",
"Porygon", "ポリゴン",
"Omanyte", "オムナイト",
"Omastar", "オムスター",
"Kabuto", "カブト",
"Kabutops", "カブトプス",
"Aerodactyl", "プテラ",
"Snorlax", "カビゴン",
"Articuno", "フリーザー",
"Zapdos", "サンダー",
"Moltres", "ファイヤー",
"Dratini", "ミニリュウ",
"Dragonair", "ハクリュー",
"Dragonite", "カイリュー",
"Mewtwo", "ミュウツー",
"Mew", "ミュウ",
"Chikorita", "チコリータ",
"Bayleef", "ベイリーフ",
"Meganium", "メガニウム",
"Cyndaquil", "ヒノアラシ",
"Quilava", "マグマラシ",
"Typhlosion", "バクフーン",
"Totodile", "ワニノコ",
"Croconaw", "アリゲイツ",
"Feraligatr", "オーダイル",
"Sentret", "オタチ",
"Furret", "オオタチ",
"Hoothoot", "ホーホー",
"Noctowl", "ヨルノズク",
"Ledyba", "レディバ",
"Ledian", "レディアン",
"Spinarak", "イトマル",
"Ariados", "アリアドス",
"Crobat", "クロバット",
"Chinchou", "チョンチー",
"Lanturn", "ランターン",
"Pichu", "ピチュー",
"Cleffa", "ピィ",
"Igglybuff", "ププリン",
"Togepi", "トゲピー",
"Togetic", "トゲチック",
"Natu", "ネイティ",
"Xatu", "ネイティオ",
"Mareep", "メリープ",
"Flaaffy", "モココ",
"Ampharos", "デンリュウ",
"Bellossom", "キレイハナ",
"Marill", "マリル",
"Azumarill", "マリルリ",
"Sudowoodo", "ウソッキー",
"Politoed", "ニョロトノ",
"Hoppip", "ハネッコ",
"Skiploom", "ポポッコ",
"Jumpluff", "ワタッコ",
"Aipom", "エイパム",
"Sunkern", "ヒマナッツ",
"Sunflora", "キマワリ",
"Yanma", "ヤンヤンマ",
"Wooper", "ウパー",
"Quagsire", "ヌオー",
"Espeon", "エーフィ",
"Umbreon", "ブラッキー",
"Murkrow", "ヤミカラス",
"Slowking", "ヤドキング",
"Misdreavus", "ムウマ",
"Unown", "アンノーン",
"Wobbuffet", "ソーナンス",
"Girafarig", "キリンリキ",
"Pineco", "クヌギダマ",
"Forretress", "フォレトス",
"Dunsparce", "ノコッチ",
"Gligar", "グライガー",
"Steelix", "ハガネール",
"Snubbull", "ブルー",
"Granbull", "グランブル",
"Qwilfish", "ハリーセン",
"Scizor", "ハッサム",
"Shuckle", "ツボツボ",
"Heracross", "ヘラクロス",
"Sneasel", "ニューラ",
"Teddiursa", "ヒメグマ",
"Ursaring", "リングマ",
"Slugma", "マグマッグ",
"Magcargo", "マグカルゴ",
"Swinub", "ウリムー",
"Piloswine", "イノムー",
"Corsola", "サニーゴ",
"Remoraid", "テッポウオ",
"Octillery", "オクタン",
"Delibird", "デリバード",
"Mantine", "マンタイン",
"Skarmory", "エアームド",
"Houndour", "デルビル",
"Houndoom", "ヘルガー",
"Kingdra", "キングドラ",
"Phanpy", "ゴマゾウ",
"Donphan", "ドンファン",
"Porygon2", "ポリゴン2",
"Stantler", "オドシシ",
"Smeargle", "ドーブル",
"Tyrogue", "バルキー",
"Hitmontop", "カポエラー",
"Smoochum", "ムチュール",
"Elekid", "エレキッド",
"Magby", "ブビィ",
"Miltank", "ミルタンク",
"Blissey", "ハピナス",
"Raikou", "ライコウ",
"Entei", "エンテイ",
"Suicune", "スイクン",
"Larvitar", "ヨーギラス",
"Pupitar", "サナギラス",
"Tyranitar", "バンギラス",
"Lugia", "ルギア",
"Ho-Oh", "ホウオウ",
"Celebi", "セレビィ",
"Treecko", "キモリ",
"Grovyle", "ジュプトル",
"Sceptile", "ジュカイン",
"Torchic", "アチャモ",
"Combusken", "ワカシャモ",
"Blaziken", "バシャーモ",
"Mudkip", "ミズゴロウ",
"Marshtomp", "ヌマクロー",
"Swampert", "ラグラージ",
"Poochyena", "ポチエナ",
"Mightyena", "グラエナ",
"Zigzagoon", "ジグザグマ",
"Linoone", "マッスグマ",
"Wurmple", "ケムッソ",
"Silcoon", "カラサリス",
"Beautifly", "アゲハント",
"Cascoon", "マユルド",
"Dustox", "ドクケイル",
"Lotad", "ハスボー",
"Lombre", "ハスブレロ",
"Ludicolo", "ルンパッパ",
"Seedot", "タネボー",
"Nuzleaf", "コノハナ",
"Shiftry", "ダーテング",
"Taillow", "スバメ",
"Swellow", "オオスバメ",
"Wingull", "キャモメ",
"Pelipper", "ペリッパー",
"Ralts", "ラルトス",
"Kirlia", "キルリア",
"Gardevoir", "サーナイト",
"Surskit", "アメタマ",
"Masquerain", "アメモース",
"Shroomish", "キノココ",
"Breloom", "キノガッサ",
"Slakoth", "ナマケロ",
"Vigoroth", "ヤルキモノ",
"Slaking", "ケッキング",
"Nincada", "ツチニン",
"Ninjask", "テッカニン",
"Shedinja", "ヌケニン",
"Whismur", "ゴニョニョ",
"Loudred", "ドゴーム",
"Exploud", "バクオング",
"Makuhita", "マクノシタ",
"Hariyama", "ハリテヤマ",
"Azurill", "ルリリ",
"Nosepass", "ノズパス",
"Skitty", "エネコ",
"Delcatty", "エネコロロ",
"Sableye", "ヤミラミ",
"Mawile", "クチート",
"Aron", "ココドラ",
"Lairon", "コドラ",
"Aggron", "ボスゴドラ",
"Meditite", "アサナン",
"Medicham", "チャーレム",
"Electrike", "ラクライ",
"Manectric", "ライボルト",
"Plusle", "プラスル",
"Minun", "マイナン",
"Volbeat", "バルビート",
"Illumise", "イルミーゼ",
"Roselia", "ロゼリア",
"Gulpin", "ゴクリン",
"Swalot", "マルノーム",
"Carvanha", "キバニア",
"Sharpedo", "サメハダー",
"Wailmer", "ホエルコ",
"Wailord", "ホエルオー",
"Numel", "ドンメル",
"Camerupt", "バクーダ",
"Torkoal", "コータス",
"Spoink", "バネブー",
"Grumpig", "ブーピッグ",
"Spinda", "パッチール",
"Trapinch", "ナックラー",
"Vibrava", "ビブラーバ",
"Flygon", "フライゴン",
"Cacnea", "サボネア",
"Cacturne", "ノクタス",
"Swablu", "チルット",
"Altaria", "チルタリス",
"Zangoose", "ザングース",
"Seviper", "ハブネーク",
"Lunatone", "ルナトーン",
"Solrock", "ソルロック",
"Barboach", "ドジョッチ",
"Whiscash", "ナマズン",
"Corphish", "ヘイガニ",
"Crawdaunt", "シザリガー",
"Baltoy", "ヤジロン",
"Claydol", "ネンドール",
"Lileep", "リリーラ",
"Cradily", "ユレイドル",
"Anorith", "アノプス",
"Armaldo", "アーマルド",
"Feebas", "ヒンバス",
"Milotic", "ミロカロス",
"Castform", "ポワルン",
"Kecleon", "カクレオン",
"Shuppet", "カゲボウズ",
"Banette", "ジュペッタ",
"Duskull", "ヨマワル",
"Dusclops", "サマヨール",
"Tropius", "トロピウス",
"Chimecho", "チリーン",
"Absol", "アブソル",
"Wynaut", "ソーナノ",
"Snorunt", "ユキワラシ",
"Glalie", "オニゴーリ",
"Spheal", "タマザラシ",
"Sealeo", "トドグラー",
"Walrein", "トドゼルガ",
"Clamperl", "パールル",
"Huntail", "ハンテール",
"Gorebyss", "サクラビス",
"Relicanth", "ジーランス",
"Luvdisc", "ラブカス",
"Bagon", "タツベイ",
"Shelgon", "コモルー",
"Salamence", "ボーマンダ",
"Beldum", "ダンバル",
"Metang", "メタング",
"Metagross", "メタグロス",
"Regirock", "レジロック",
"Regice", "レジアイス",
"Registeel", "レジスチル",
"Latias", "ラティアス",
"Latios", "ラティオス",
"Kyogre", "カイオーガ",
"Groudon", "グラードン",
"Rayquaza", "レックウザ",
"Jirachi", "ジラーチ",
"Deoxys", "デオキシス",
"Turtwig", "ナエトル",
"Grotle", "ハヤシガメ",
"Torterra", "ドダイトス",
"Chimchar", "ヒコザル",
"Monferno", "モウカザル",
"Infernape", "ゴウカザル",
"Piplup", "ポッチャマ",
"Prinplup", "ポッタイシ",
"Empoleon", "エンペルト",
"Starly", "ムックル",
"Staravia", "ムクバード",
"Staraptor", "ムクホーク",
"Bidoof", "ビッパ",
"Bibarel", "ビーダル",
"Kricketot", "コロボーシ",
"Kricketune", "コロトック",
"Shinx", "コリンク",
"Luxio", "ルクシオ",
"Luxray", "レントラー",
"Budew", "スボミー",
"Roserade", "ロズレイド",
"Cranidos", "ズガイドス",
"Rampardos", "ラムパルド",
"Shieldon", "タテトプス",
"Bastiodon", "トリデプス",
"Burmy", "ミノムッチ",
"Wormadam", "ミノマダム",
"Mothim", "ガーメイル",
"Combee", "ミツハニー",
"Vespiquen", "ビークイン",
"Pachirisu", "パチリス",
"Buizel", "ブイゼル",
"Floatzel", "フローゼル",
"Cherubi", "チェリンボ",
"Cherrim", "チェリム",
"Shellos", "カラナクシ",
"Gastrodon", "トリトドン",
"Ambipom", "エテボース",
"Drifloon", "フワンテ",
"Drifblim", "フワライド",
"Buneary", "ミミロル",
"Lopunny", "ミミロップ",
"Mismagius", "ムウマージ",
"Honchkrow", "ドンカラス",
"Glameow", "ニャルマー",
"Purugly", "ブニャット",
"Chingling", "リーシャン",
"Stunky", "スカンプー",
"Skuntank", "スカタンク",
"Bronzor", "ドーミラー",
"Bronzong", "ドータクン",
"Bonsly", "ウソハチ",
"Mime Jr.", "マネネ",
"Happiny", "ピンプク",
"Chatot", "ペラップ",
"Spiritomb", "ミカルゲ",
"Gible", "フカマル",
"Gabite", "ガバイト",
"Garchomp", "ガブリアス",
"Munchlax", "ゴンベ",
"Riolu", "リオル",
"Lucario", "ルカリオ",
"Hippopotas", "ヒポポタス",
"Hippowdon", "カバルドン",
"Skorupi", "スコルピ",
"Drapion", "ドラピオン",
"Croagunk", "グレッグル",
"Toxicroak", "ドクロッグ",
"Carnivine", "マスキッパ",
"Finneon", "ケイコウオ",
"Lumineon", "ネオラント",
"Mantyke", "タマンタ",
"Snover", "ユキカブリ",
"Abomasnow", "ユキノオー",
"Weavile", "マニューラ",
"Magnezone", "ジバコイル",
"Lickilicky", "ベロベルト",
"Rhyperior", "ドサイドン",
"Tangrowth", "モジャンボ",
"Electivire", "エレキブル",
"Magmortar", "ブーバーン",
"Togekiss", "トゲキッス",
"Yanmega", "メガヤンマ",
"Leafeon", "リーフィア",
"Glaceon", "グレイシア",
"Gliscor", "グライオン",
"Mamoswine", "マンムー",
"Porygon-Z", "ポリゴンZ",
"Gallade", "エルレイド",
"Probopass", "ダイノーズ",
"Dusknoir", "ヨノワール",
"Froslass", "ユキメノコ",
"Rotom", "ロトム",
"Uxie", "ユクシー",
"Mesprit", "エムリット",
"Azelf", "アグノム",
"Dialga", "ディアルガ",
"Palkia", "パルキア",
"Heatran", "ヒードラン",
"Regigigas", "レジギガス",
"Giratina", "ギラティナ",
"Cresselia", "クレセリア",
"Phione", "フィオネ",
"Manaphy", "マナフィ",
"Darkrai", "ダークライ",
"Shaymin", "シェイミ",
"Arceus", "アルセウス",
"Victini", "ビクティニ",
"Snivy", "ツタージャ",
"Servine", "ジャノビー",
"Serperior", "ジャローダ",
"Tepig", "ポカブ",
"Pignite", "チャオブー",
"Emboar", "エンブオー",
"Oshawott", "ミジュマル",
"Dewott", "フタチマル",
"Samurott", "ダイケンキ",
"Patrat", "ミネズミ",
"Watchog", "ミルホッグ",
"Lillipup", "ヨーテリー",
"Herdier", "ハーデリア",
"Stoutland", "ムーランド",
"Purrloin", "チョロネコ",
"Liepard", "レパルダス",
"Pansage", "ヤナップ",
"Simisage", "ヤナッキー",
"Pansear", "バオップ",
"Simisear", "バオッキー",
"Panpour", "ヒヤップ",
"Simipour", "ヒヤッキー",
"Munna", "ムンナ",
"Musharna", "ムシャーナ",
"Pidove", "マメパト",
"Tranquill", "ハトーボー",
"Unfezant", "ケンホロウ",
"Blitzle", "シママ",
"Zebstrika", "ゼブライカ",
"Roggenrola", "ダンゴロ",
"Boldore", "ガントル",
"Gigalith", "ギガイアス",
"Woobat", "コロモリ",
"Swoobat", "ココロモリ",
"Drilbur", "モグリュー",
"Excadrill", "ドリュウズ",
"Audino", "タブンネ",
"Timburr", "ドッコラー",
"Gurdurr", "ドテッコツ",
"Conkeldurr", "ローブシン",
"Tympole", "オタマロ",
"Palpitoad", "ガマガル",
"Seismitoad", "ガマゲロゲ",
"Throh", "ナゲキ",
"Sawk", "ダゲキ",
"Sewaddle", "クルミル",
"Swadloon", "クルマユ",
"Leavanny", "ハハコモリ",
"Venipede", "フシデ",
"Whirlipede", "ホイーガ",
"Scolipede", "ペンドラー",
"Cottonee", "モンメン",
"Whimsicott", "エルフーン",
"Petilil", "チュリネ",
"Lilligant", "ドレディア",
"Basculin", "バスラオ",
"Sandile", "メグロコ",
"Krokorok", "ワルビル",
"Krookodile", "ワルビアル",
"Darumaka", "ダルマッカ",
"Darmanitan", "ヒヒダルマ",
"Maractus", "マラカッチ",
"Dwebble", "イシズマイ",
"Crustle", "イワパレス",
"Scraggy", "ズルッグ",
"Scrafty", "ズルズキン",
"Sigilyph", "シンボラー",
"Yamask", "デスマス",
"Cofagrigus", "デスカーン",
"Tirtouga", "プロトーガ",
"Carracosta", "アバゴーラ",
"Archen", "アーケン",
"Archeops", "アーケオス",
"Trubbish", "ヤブクロン",
"Garbodor", "ダストダス",
"Zorua", "ゾロア",
"Zoroark", "ゾロアーク",
"Minccino", "チラーミィ",
"Cinccino", "チラチーノ",
"Gothita", "ゴチム",
"Gothorita", "ゴチミル",
"Gothitelle", "ゴチルゼル",
"Solosis", "ユニラン",
"Duosion", "ダブラン",
"Reuniclus", "ランクルス",
"Ducklett", "コアルヒー",
"Swanna", "スワンナ",
"Vanillite", "バニプッチ",
"Vanillish", "バニリッチ",
"Vanilluxe", "バイバニラ",
"Deerling", "シキジカ",
"Sawsbuck", "メブキジカ",
"Emolga", "エモンガ",
"Karrablast", "カブルモ",
"Escavalier", "シュバルゴ",
"Foongus", "タマゲタケ",
"Amoonguss", "モロバレル",
"Frillish", "プルリル",
"Jellicent", "ブルンゲル",
"Alomomola", "ママンボウ",
"Joltik", "バチュル",
"Galvantula", "デンチュラ",
"Ferroseed", "テッシード",
"Ferrothorn", "ナットレイ",
"Klink", "ギアル",
"Klang", "ギギアル",
"Klinklang", "ギギギアル",
"Tynamo", "シビシラス",
"Eelektrik", "シビビール",
"Eelektross", "シビルドン",
"Elgyem", "リグレー",
"Beheeyem", "オーベム",
"Litwick", "ヒトモシ",
"Lampent", "ランプラー",
"Chandelure", "シャンデラ",
"Axew", "キバゴ",
"Fraxure", "オノンド",
"Haxorus", "オノノクス",
"Cubchoo", "クマシュン",
"Beartic", "ツンベアー",
"Cryogonal", "フリージオ",
"Shelmet", "チョボマキ",
"Accelgor", "アギルダー",
"Stunfisk", "マッギョ",
"Mienfoo", "コジョフー",
"Mienshao", "コジョンド",
"Druddigon", "クリムガン",
"Golett", "ゴビット",
"Golurk", "ゴルーグ",
"Pawniard", "コマタナ",
"Bisharp", "キリキザン",
"Bouffalant", "バッフロン",
"Rufflet", "ワシボン",
"Braviary", "ウォーグル",
"Vullaby", "バルチャイ",
"Mandibuzz", "バルジーナ",
"Heatmor", "クイタラン",
"Durant", "アイアント",
"Deino", "モノズ",
"Zweilous", "ジヘッド",
"Hydreigon", "サザンドラ",
"Larvesta", "メラルバ",
"Volcarona", "ウルガモス",
"Cobalion", "コバルオン",
"Terrakion", "テラキオン",
"Virizion", "ビリジオン",
"Tornadus", "トルネロス",
"Thundurus", "ボルトロス",
"Reshiram", "レシラム",
"Zekrom", "ゼクロム",
"Landorus", "ランドロス",
"Kyurem", "キュレム",
"Keldeo", "ケルディオ",
"Meloetta", "メロエッタ",
"Genesect", "ゲノセクト",
"Chespin", "ハリマロン",
"Quilladin", "ハリボーグ",
"Chesnaught", "ブリガロン",
"Fennekin", "フォッコ",
"Braixen", "テールナー",
"Delphox", "マフォクシー",
"Froakie", "ケロマツ",
"Frogadier", "ゲコガシラ",
"Greninja", "ゲッコウガ",
"Bunnelby", "ホルビー",
"Diggersby", "ホルード",
"Fletchling", "ヤヤコマ",
"Fletchinder", "ヒノヤコマ",
"Talonflame", "ファイアロー",
"Scatterbug", "コフキムシ",
"Spewpa", "コフーライ",
"Vivillon", "ビビヨン",
"Litleo", "シシコ",
"Pyroar", "カエンジシ",
"Flabébé", "フラベベ",
"Floette", "フラエッテ",
"Florges", "フラージェス",
"Skiddo", "メェークル",
"Gogoat", "ゴーゴート",
"Pancham", "ヤンチャム",
"Pangoro", "ゴロンダ",
"Furfrou", "トリミアン",
"Espurr", "ニャスパー",
"Meowstic", "ニャオニクス",
"Honedge", "ヒトツキ",
"Doublade", "ニダンギル",
"Aegislash", "ギルガルド",
"Spritzee", "シュシュプ",
"Aromatisse", "フレフワン",
"Swirlix", "ペロッパフ",
"Slurpuff", "ペロリーム",
"Inkay", "マーイーカ",
"Malamar", "カラマネロ",
"Binacle", "カメテテ",
"Barbaracle", "ガメノデス",
"Skrelp", "クズモー",
"Dragalge", "ドラミドロ",
"Clauncher", "ウデッポウ",
"Clawitzer", "ブロスター",
"Helioptile", "エリキテル",
"Heliolisk", "エレザード",
"Tyrunt", "チゴラス",
"Tyrantrum", "ガチゴラス",
"Amaura", "アマルス",
"Aurorus", "アマルルガ",
"Sylveon", "ニンフィア",
"Hawlucha", "ルチャブル",
"Dedenne", "デデンネ",
"Carbink", "メレシー",
"Goomy", "ヌメラ",
"Sliggoo", "ヌメイル",
"Goodra", "ヌメルゴン",
"Klefki", "クレッフィ",
"Phantump", "ボクレー",
"Trevenant", "オーロット",
"Pumpkaboo", "バケッチャ",
"Gourgeist", "パンプジン",
"Bergmite", "カチコール",
"Avalugg", "クレベース",
"Noibat", "オンバット",
"Noivern", "オンバーン",
"Xerneas", "ゼルネアス",
"Yveltal", "イベルタル",
"Zygarde", "ジガルデ",
"Diancie", "ディアンシー",
"Hoopa", "フーパ",
"Volcanion", "ボルケニオン",
"Rowlet", "モクロー",
"Dartrix", "フクスロー",
"Decidueye", "ジュナイパー",
"Litten", "ニャビー",
"Torracat", "ニャヒート",
"Incineroar", "ガオガエン",
"Popplio", "アシマリ",
"Brionne", "オシャマリ",
"Primarina", "アシレーヌ",
"Pikipek", "ツツケラ",
"Trumbeak", "ケララッパ",
"Toucannon", "ドデカバシ",
"Yungoos", "ヤングース",
"Gumshoos", "デカグース",
"Grubbin", "アゴジムシ",
"Charjabug", "デンヂムシ",
"Vikavolt", "クワガノン",
"Crabrawler", "マケンカニ",
"Crabominable", "ケケンカニ",
"Oricorio", "オドリドリ",
"Cutiefly", "アブリー",
"Ribombee", "アブリボン",
"Rockruff", "イワンコ",
"Lycanroc", "ルガルガン",
"Wishiwashi", "ヨワシ",
"Mareanie", "ヒドイデ",
"Toxapex", "ドヒドイデ",
"Mudbray", "ドロバンコ",
"Mudsdale", "バンバドロ",
"Dewpider", "シズクモ",
"Araquanid", "オニシズクモ",
"Fomantis", "カリキリ",
"Lurantis", "ラランテス",
"Morelull", "ネマシュ",
"Shiinotic", "マシェード",
"Salandit", "ヤトウモリ",
"Salazzle", "エンニュート",
"Stufful", "ヌイコグマ",
"Bewear", "キテルグマ",
"Bounsweet", "アマカジ",
"Steenee", "アママイコ",
"Tsareena", "アマージョ",
"Comfey", "キュワワー",
"Oranguru", "ヤレユータン",
"Passimian", "ナゲツケサル",
"Wimpod", "コソクムシ",
"Golisopod", "グソクムシャ",
"Sandygast", "スナバァ",
"Palossand", "シロデスナ",
"Pyukumuku", "ナマコブシ",
"Type: Null", "タイプ：ヌル",
"Silvally", "シルヴァディ",
"Minior", "メテノ",
"Komala", "ネッコアラ",
"Turtonator", "バクガメス",
"Togedemaru", "トゲデマル",
"Mimikyu", "ミミッキュ",
"Bruxish", "ハギギシリ",
"Drampa", "ジジーロン",
"Dhelmise", "ダダリン",
"Jangmo-o", "ジャラコ",
"Hakamo-o", "ジャランゴ",
"Kommo-o", "ジャラランガ",
"Tapu Koko", "カプ・コケコ",
"Tapu Lele", "カプ・テテフ",
"Tapu Bulu", "カプ・ブルル",
"Tapu Fini", "カプ・レヒレ",
"Cosmog", "コスモッグ",
"Cosmoem", "コスモウム",
"Solgaleo", "ソルガレオ",
"Lunala", "ルナアーラ",
"Nihilego", "ウツロイド",
"Buzzwole", "マッシブーン",
"Pheromosa", "フェローチェ",
"Xurkitree", "デンジュモク",
"Celesteela", "テッカグヤ",
"Kartana", "カミツルギ",
"Guzzlord", "アクジキング",
"Necrozma", "ネクロズマ",
"Magearna", "マギアナ",
"Marshadow", "マーシャドー",
"Poipole", "ベベノム",
"Naganadel", "アーゴヨン",
"Stakataka", "ツンデツンデ",
"Blacephalon", "ズガドーン",
"Zeraora", "ゼラオラ",
"Meltan", "メルタン",
"Melmetal", "メルメタル",
"Grookey", "サルノリ",
"Thwackey", "バチンキー",
"Rillaboom", "ゴリランダー",
"Scorbunny", "ヒバニー",
"Raboot", "ラビフット",
"Cinderace", "エースバーン",
"Sobble", "メッソン",
"Drizzile", "ジメレオン",
"Inteleon", "インテレオン",
"Skwovet", "ホシガリス",
"Greedent", "ヨクバリス",
"Rookidee", "ココガラ",
"Corvisquire", "アオガラス",
"Corviknight", "アーマーガア",
"Blipbug", "サッチムシ",
"Dottler", "レドームシ",
"Orbeetle", "イオルブ",
"Nickit", "クスネ",
"Thievul", "フォクスライ",
"Gossifleur", "ヒメンカ",
"Eldegoss", "ワタシラガ",
"Wooloo", "ウールー",
"Dubwool", "バイウールー",
"Chewtle", "カムカメ",
"Drednaw", "カジリガメ",
"Yamper", "ワンパチ",
"Boltund", "パルスワン",
"Rolycoly", "タンドン",
"Carkol", "トロッゴン",
"Coalossal", "セキタンザン",
"Applin", "カジッチュ",
"Flapple", "アップリュー",
"Appletun", "タルップル",
"Silicobra", "スナヘビ",
"Sandaconda", "サダイジャ",
"Cramorant", "ウッウ",
"Arrokuda", "サシカマス",
"Barraskewda", "カマスジョー",
"Toxel", "エレズン",
"Toxtricity", "ストリンダー",
"Sizzlipede", "ヤクデ",
"Centiskorch", "マルヤクデ",
"Clobbopus", "タタッコ",
"Grapploct", "オトスパス",
"Sinistea", "ヤバチャ",
"Polteageist", "ポットデス",
"Hatenna", "ミブリム",
"Hattrem", "テブリム",
"Hatterene", "ブリムオン",
"Impidimp", "ベロバー",
"Morgrem", "ギモー",
"Grimmsnarl", "オーロンゲ",
"Obstagoon", "タチフサグマ",
"Perrserker", "ニャイキング",
"Cursola", "サニゴーン",
"Sirfetch'd", "ネギガナイト",
"Mr. Rime", "バリコオル",
"Runerigus", "デスバーン",
"Milcery", "マホミル",
"Alcremie", "マホイップ",
"Falinks", "タイレーツ",
"Pincurchin", "バチンウニ",
"Snom", "ユキハミ",
"Frosmoth", "モスノウ",
"Stonjourner", "イシヘンジン",
"Eiscue", "コオリッポ",
"Indeedee", "イエッサン",
"Morpeko", "モルペコ",
"Cufant", "ゾウドウ",
"Copperajah", "ダイオウドウ",
"Dracozolt", "パッチラゴン",
"Arctozolt", "パッチルドン",
"Dracovish", "ウオノラゴン",
"Arctovish", "ウオチルドン",
"Duraludon", "ジュラルドン",
"Dreepy", "ドラメシヤ",
"Drakloak", "ドロンチ",
"Dragapult", "ドラパルト",
"Zacian", "ザシアン",
"Zamazenta", "ザマゼンタ",
"Eternatus", "ムゲンダイナ",
"Kubfu", "ダクマ",
"Urshifu", "ウーラオス",
"Zarude", "ザルード",
"Regieleki", "レジエレキ",
"Regidrago", "レジドラゴ",
"Glastrier", "ブリザポス",
"Spectrier", "レイスポス",
"Calyrex", "バドレックス",
"Wyrdeer", "アヤシシ",
"Kleavor", "バサギリ",
"Ursaluna", "ガチグマ",
"Basculegion", "イダイトウ",
"Sneasler", "オオニューラ",
"Overqwil", "ハリーマン",
"Enamorus", "ラブトロス",
"Sprigatito", "ニャオハ",
"Floragato", "ニャローテ",
"Meowscarada", "マスカーニャ",
"Fuecoco", "ホゲータ",
"Crocalor", "アチゲータ",
"Skeledirge", "ラウドボーン",
"Quaxly", "クワッス",
"Quaxwell", "ウェルカモ",
"Quaquaval", "ウェーニバル",
"Lechonk", "グルトン",
"Oinkologne", "パフュートン",
"Tarountula", "タマンチュラ",
"Spidops", "ワナイダー",
"Nymble", "マメバッタ",
"Lokix", "エクスレッグ",
"Pawmi", "パモ",
"Pawmo", "パモット",
"Pawmot", "パーモット",
"Tandemaus", "ワッカネズミ",
"Maushold", "イッカネズミ",
"Fidough", "パピモッチ",
"Dachsbun", "バウッツェル",
"Smoliv", "ミニーブ",
"Dolliv", "オリーニョ",
"Arboliva", "オリーヴァ",
"Squawkabilly", "イキリンコ",
"Nacli", "コジオ",
"Naclstack", "ジオヅム",
"Garganacl", "キョジオーン",
"Charcadet", "カルボウ",
"Armarouge", "グレンアルマ",
"Ceruledge", "ソウブレイズ",
"Tadbulb", "ズピカ",
"Bellibolt", "ハラバリー",
"Wattrel", "カイデン",
"Kilowattrel", "タイカイデン",
"Maschiff", "オラチフ",
"Mabosstiff", "マフィティフ",
"Shroodle", "シルシュルー",
"Grafaiai", "タギングル",
"Bramblin", "アノクサ",
"Brambleghast", "アノホラグサ",
"Toedscool", "ノノクラゲ",
"Toedscruel", "リククラゲ",
"Klawf", "ガケガニ",
"Capsakid", "カプサイジ",
"Scovillain", "スコヴィラン",
"Rellor", "シガロコ",
"Rabsca", "ベラカス",
"Flittle", "ヒラヒナ",
"Espathra", "クエスパトラ",
"Tinkatink", "カヌチャン",
"Tinkatuff", "ナカヌチャン",
"Tinkaton", "デカヌチャン",
"Wiglett", "ウミディグダ",
"Wugtrio", "ウミトリオ",
"Bombirdier", "オトシドリ",
"Finizen", "ナミイルカ",
"Palafin", "イルカマン",
"Varoom", "ブロロン",
"Revavroom", "ブロロローム",
"Cyclizar", "モトトカゲ",
"Orthworm", "ミミズズ",
"Glimmet", "キラーメ",
"Glimmora", "キラフロル",
"Greavard", "ボチ",
"Houndstone", "ハカドッグ",
"Flamigo", "カラミンゴ",
"Cetoddle", "アルクジラ",
"Cetitan", "ハルクジラ",
"Veluza", "ミガルーサ",
"Dondozo", "ヘイラッシャ",
"Tatsugiri", "シャリタツ",
"Annihilape", "コノヨザル",
"Clodsire", "ドオー",
"Farigiraf", "リキキリン",
"Dudunsparce", "ノココッチ",
"Kingambit", "ドドゲザン",
"Great Tusk", "イダイナキバ",
"Scream Tail", "サケブシッポ",
"Brute Bonnet", "アラブルタケ",
"Flutter Mane", "ハバタクカミ",
"Slither Wing", "チヲハウハネ",
"Sandy Shocks", "スナノケガワ",
"Iron Treads", "テツノワダチ",
"Iron Bundle", "テツノツツミ",
"Iron Hands", "テツノカイナ",
"Iron Jugulis", "テツノコウベ",
"Iron Moth", "テツノドクガ",
"Iron Thorns", "テツノイバラ",
"Frigibax", "セビエ",
"Arctibax", "セゴール",
"Baxcalibur", "セグレイブ",
"Gimmighoul", "コレクレー",
"Gholdengo", "サーフゴー",
"Wo-Chien", "チオンジェン",
"Chien-Pao", "パオジアン",
"Ting-Lu", "ディンルー",
"Chi-Yu", "イーユイ",
"Roaring Moon", "トドロクツキ",
"Iron Valiant", "テツノブジン",
"Koraidon", "コライドン",
"Miraidon", "ミライドン",
"Walking Wake", "ウネルミナモ",
"Iron Leaves", "テツノイサハ",
"Dipplin", "カミッチュ",
"Poltchageist", "チャデス",
"Sinistcha", "ヤバソチャ",
"Okidogi", "イイネイヌ",
"Munkidori", "マシマシラ",
"Fezandipiti", "キチキギス",
"Ogerpon", "オーガポン",
"Archaludon", "ブリジュラス",
"Hydrapple", "カミツオロチ",
"Gouging Fire", "ウガツホムラ",
"Raging Bolt", "タケルライコ",
"Iron Boulder", "テツノイワオ",
"Iron Crown", "テツノカシラ",
"Terapagos", "テラパゴス",
"Pecharunt", "モモワロウ",
        # ここに追加していく
    ]
    
    has_pokemon = any(t in POKEMON_NAMES_ONLY for t in tags)
    

    gender_found = False

    for female in FEMALE_TRAINERS:
        if re.search(r'\b' + female + r'\b', title_upper):
            if not has_pokemon:
                tags.append("女トレーナー")
                gender_found = True
            break

    if not gender_found:
        for male in MALE_TRAINERS:
            if re.search(r'\b' + male + r'\b', title_upper):
                if not has_pokemon:
                    tags.append("男トレーナー")
                break
    return tags

if __name__ == "__main__":
    test_titles = [
        "PSA 10 Pikachu 2025 Japanese Pokemon Card",
        "Char izard PSA 10 Japanese",
        "PSA 10 MEWTWO Japanese Holo",
        "PSA 10 Mew Japanese Holo",
        "PSA 10 Some Unknown Card Japanese",
        "Ho-Oh PSA 10 Japanese Rainbow Rare",
        "Giovanni Boss Promo PSA 10 Japanese",
    ]
    for title in test_titles:
        tags = get_tags(title)
        print(f"タイトル：{title}")
        print(f"タグ　　：{tags}")
        print("-" * 50)